/**
 * Apply Supplier Descriptions
 *
 * Updates all suppliers with 150+ word SEO descriptions.
 * Each description is unique and tailored to the supplier.
 *
 * Usage:
 *   cd api && npx dotenv -e .env.prod -- ts-node --transpile-only scripts/apply-supplier-descriptions.ts
 *   cd api && npx dotenv -e .env.prod -- ts-node --transpile-only scripts/apply-supplier-descriptions.ts --dry-run
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const DRY_RUN = process.argv.includes('--dry-run');

// Map of supplier ID -> new description (150+ words each)
const DESCRIPTIONS: Record<number, string> = {
  2: `B-Stock operates one of the largest B2B liquidation auction platforms in the United States, connecting major retailers and manufacturers directly with vetted wholesale buyers. Based in San Mateo, California, the company has built proprietary marketplace technology that powers branded auction sites for Fortune 500 retailers including Amazon, Walmart, Target, Home Depot, and dozens more. Buyers bid on manifested lots of customer returns, overstock, and refurbished merchandise across every major product category, from consumer electronics and home appliances to apparel, health and beauty, and general merchandise. B-Stock's platform supports pallet-level and truckload-level purchasing, with lot sizes ranging from a few hundred dollars to six-figure truckload buys. All transactions are conducted online through a transparent auction format with detailed manifests, condition grading, and estimated retail values. The company serves a broad buyer base including Amazon FBA sellers, eBay resellers, bin store operators, discount retailers, and international export buyers. Warehouse locations across multiple states enable regional pickup and cost-effective freight options for domestic and overseas shipments.`,

  3: `Liquidation.com is a flagship marketplace operated by Liquidity Services, one of the longest-running and most established names in the surplus and returns industry. Headquartered in Bethesda, Maryland, the platform conducts thousands of online auctions weekly, offering manifested and unmanifested pallets, truckloads, and case-pack lots sourced from federal government agencies, Fortune 500 retailers, and major manufacturers. Product categories span consumer electronics, computers, clothing, vehicles, industrial equipment, and general merchandise. The auction format provides transparent bidding with detailed lot descriptions, photographs, condition reports, and estimated retail values. Buyers range from small resellers and flea market vendors to large-scale export operations and discount retail chains. Liquidation.com maintains multiple warehouse locations across the United States, supporting both will-call pickup and nationwide freight delivery with dock-high and liftgate options. The platform's buyer verification process and dispute resolution system provide added protection for both sides of each transaction, making it a trusted starting point for newcomers entering the liquidation industry.`,

  4: `Direct Liquidation provides a B2B auction marketplace that connects wholesale buyers with manifested pallets and full truckloads sourced directly from major U.S. retailers. Operating from Bentonville, Arkansas, the company specializes in customer returns, shelf pulls, and overstock merchandise from some of the nation's largest retail chains. Product categories include electronics, home goods, toys, sporting goods, tools, and general merchandise, with lots ranging from single pallets to full fifty-three-foot truckloads. Each auction listing includes detailed manifests with item-level descriptions, UPC codes, and estimated retail values, giving buyers the transparency needed to calculate potential profit margins before bidding. Direct Liquidation serves a diverse buyer community including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, and discount retail chains across the United States and internationally. The company offers flexible shipping options including regional freight, LTL, and full truckload delivery, as well as warehouse pickup for local buyers looking to minimize logistics costs and inspect merchandise in person before purchasing.`,

  5: `Via Trading has built a reputation as one of the most established wholesale liquidation suppliers on the West Coast, operating from a large warehouse facility in Lynwood, California, just outside Los Angeles. The company specializes in customer returns, overstock, and shelf-pull merchandise sourced from major national retailers, offering buyers a wide selection of pallets and truckloads across categories including electronics, toys, housewares, health and beauty, sporting goods, tools, and general merchandise. Via Trading is known for its transparent pricing model and detailed lot descriptions that include estimated retail values, item counts, and condition grades. The company serves a broad buyer base that includes Amazon and eBay resellers, bin store operators, flea market vendors, discount retailers, and international export buyers who consolidate shipments from the Lynwood facility. Warehouse pickup is available for local buyers, and nationwide freight shipping is offered with both LTL and full truckload options. Via Trading's proximity to the Port of Long Beach makes it particularly convenient for export buyers assembling ocean containers for overseas markets.`,

  6: `Quicklotz is a high-volume wholesale liquidation platform headquartered in Fort Worth, Texas, that specializes in selling customer returns and overstock inventory by the pallet and truckload. The company sources merchandise from major U.S. retailers including Amazon, Walmart, Target, and other national chains, offering an ever-rotating inventory of electronics, home goods, toys, apparel, health and beauty products, and general merchandise. Quicklotz is known for its competitive pallet pricing, with options ranging from manifested lots with full item visibility to lower-cost unmanifested pallets for buyers comfortable with some product variability. The Fort Worth location provides central U.S. positioning that keeps freight costs reasonable for buyers shipping to either coast or throughout the Southeast and Midwest. Quicklotz serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and discount store owners. The company offers warehouse pickup, regional freight delivery, and full truckload shipping, with a user-friendly online ordering platform that allows buyers to browse available inventory, place orders, and track shipments.`,

  7: `Fr8Auctions operates an online liquidation auction platform out of Atlanta, Georgia, connecting wholesale buyers with pallets and truckloads of returns, overstock, and closeout merchandise from major U.S. retailers. The company's auction-based format allows buyers to bid competitively on manifested lots across popular categories including electronics, home and garden, toys, apparel, health and beauty, tools, and general merchandise. Each listing includes detailed information about product condition, estimated retail value, and item counts to help buyers assess profit potential before placing bids. Fr8Auctions' Atlanta location positions it at a major freight crossroads in the Southeast, keeping shipping costs competitive for buyers throughout the eastern United States. The platform serves a wide range of buyers including Amazon FBA resellers, eBay sellers, bin store operators, flea market vendors, dollar store owners, and international export buyers. Fr8Auctions provides both warehouse pickup for local buyers and nationwide freight delivery options including LTL and full truckload shipping with dock-high loading capabilities.`,

  8: `Department Store Liquidations is a wholesale liquidation supplier based in New York, New York, specializing in closeout and overstock merchandise from major department store chains across the United States. The company sources inventory directly from well-known retailers, offering buyers pallets and truckloads of apparel, shoes, accessories, home decor, housewares, beauty products, and designer merchandise at significant discounts below wholesale cost. With deep roots in the New York garment and retail district, Department Store Liquidations has established sourcing relationships that provide consistent access to brand-name and designer merchandise that rarely appears through other liquidation channels. The company serves boutique retailers, online resellers, consignment shop owners, bin store operators, and export buyers who ship container loads to international markets. Its Northeast location near major ports and interstate corridors makes it convenient for buyers throughout the tri-state area and beyond. Department Store Liquidations offers warehouse pickup, regional delivery, and full truckload shipping options for buyers looking to source premium department store inventory.`,

  9: `JD Closeouts operates from Hollywood, Florida, as a wholesale liquidation supplier focused on delivering quality customer returns, shelf pulls, and overstock merchandise at deep discounts. The company sources inventory from major U.S. retailers and offers pallets and truckloads across a broad range of categories including electronics, home goods, toys, health and beauty, tools, sporting goods, and general merchandise. JD Closeouts is known for providing detailed manifests and condition reports with each lot, giving buyers the transparency they need to evaluate potential margins before purchasing. The South Florida location serves as a natural hub for both domestic resale buyers and international export operations, with proximity to the Port of Miami and Fort Lauderdale enabling cost-effective container shipping to Latin America, the Caribbean, and beyond. JD Closeouts serves Amazon FBA sellers, eBay resellers, flea market vendors, bin store operators, discount retailers, and wholesale export buyers. The company provides warehouse pickup, LTL freight delivery, and full truckload shipping throughout the continental United States.`,

  10: `Merchandize Liquidators operates from Charlotte, North Carolina, offering wholesale pallets and truckloads of liquidation merchandise sourced from major national retailers and brand manufacturers. The company handles customer returns, overstock, shelf pulls, and closeout inventory across categories including electronics, home goods, toys, apparel, health and beauty, tools, and general merchandise. Merchandize Liquidators is known for its consistent inventory pipeline and transparent lot descriptions that include estimated retail values, item counts, and condition assessments. The Charlotte location positions the company at a strategic logistics crossroads in the Southeast, with easy access to I-77 and I-85 for cost-effective shipping throughout the eastern United States. The company serves a diverse buyer base including Amazon and eBay resellers, Whatnot sellers, bin store operators, flea market vendors, discount store owners, and international export buyers. Merchandize Liquidators offers flexible purchasing options from single pallets to full truckloads, with warehouse pickup available for local buyers and nationwide freight delivery for remote customers.`,

  11: `Discount Wholesalers Inc operates from Lumberton, North Carolina, as a wholesale liquidation company specializing in customer returns, overstock, and closeout merchandise sourced from major U.S. retail chains. The company offers a wide selection of pallets and truckloads across popular categories including electronics, home goods, toys, tools, sporting goods, health and beauty products, and general merchandise. Discount Wholesalers is known for competitive pricing that attracts both new and experienced liquidation buyers, with lot options ranging from small mixed pallets for startup resellers to full truckloads for high-volume buyers. The Lumberton location provides affordable warehouse space and competitive freight rates throughout the Southeast and Mid-Atlantic regions. The company serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, flea market vendors, bin store operators, and discount retail chains. Discount Wholesalers offers warehouse pickup for local buyers and arranges LTL and full truckload delivery to destinations across the continental United States.`,

  12: `DNC Wholesale operates out of Pompano Beach, Florida, as a wholesale liquidation supplier focused on pallets and truckloads of customer returns, overstock, and closeout merchandise from top national retailers. The company carries a broad product mix spanning electronics, home goods, health and beauty, toys, apparel, housewares, and general merchandise, with new inventory arriving on a regular basis. DNC Wholesale caters to both domestic resellers and international export buyers who take advantage of the company's proximity to South Florida ports for container consolidation and overseas shipping. Lot options range from single pallets ideal for new resellers testing the market to full fifty-three-foot truckloads for established high-volume operations. Each lot includes condition descriptions and estimated retail values to help buyers assess their potential return on investment. DNC Wholesale serves bin store operators, eBay and Amazon resellers, flea market vendors, dollar store owners, and discount retail chains across the United States, Caribbean, and Latin America. The company offers warehouse pickup and nationwide freight delivery.`,

  13: `RL Liquidators is a wholesale liquidation supplier based in Sacramento, California, specializing in customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company offers pallets and truckloads of merchandise spanning electronics, home improvement, toys, health and beauty, apparel, outdoor equipment, and general merchandise. RL Liquidators is known for its competitive West Coast pricing and consistent inventory availability, making it a go-to source for California-based resellers and buyers throughout the western United States. The Sacramento location provides strategic positioning between the San Francisco Bay Area and the Central Valley, with convenient access to major interstate corridors for both local pickup and long-haul freight. The company serves Amazon FBA sellers, eBay resellers, Whatnot sellers, bin store operators, flea market vendors, and discount store owners. RL Liquidators offers flexible lot sizes from single-pallet purchases to multi-pallet and full truckload orders, with warehouse pickup and freight delivery options available to meet different buyer needs and budgets.`,

  14: `Inmar Liquidates is a subsidiary of Inmar Intelligence, a major supply chain technology company headquartered in Winston-Salem, North Carolina. The company operates one of the largest reverse logistics networks in the United States, processing billions of dollars in returned and excess merchandise annually for major retail chains, pharmacies, and consumer goods manufacturers. Inmar Liquidates offers wholesale buyers access to manifested pallets and truckloads of customer returns, overstock, and recalled products across categories including health care, beauty, grocery, general merchandise, electronics, and consumer packaged goods. The company's technology-driven approach provides detailed product manifests, condition grading, and compliance documentation that sets it apart from many independent liquidation suppliers. Inmar Liquidates serves a broad range of buyers including discount retailers, secondary market distributors, online resellers, bin store operators, and international export operations. With processing facilities across multiple states, the company offers flexible shipping and pickup options designed to minimize freight costs for buyers regardless of their geographic location.`,

  15: `Select Liquidation operates from Texas City, Texas, as a wholesale liquidation supplier offering pallets and truckloads of customer returns, overstock, and closeout merchandise sourced from major retailers. The company handles a diverse product mix including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with new inventory arriving regularly to keep selection fresh for repeat buyers. Select Liquidation's Texas Gulf Coast location provides competitive freight rates for buyers throughout the South, Southwest, and Midwest, while also enabling convenient access for international export buyers shipping through the Port of Houston. The company offers both manifested and unmanifested lot options at different price points, allowing buyers to choose the level of product visibility that fits their business model and risk tolerance. Select Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and discount store owners across the United States. Warehouse pickup and nationwide freight delivery are both available for all lot sizes.`,

  16: `888 Lots is a B2B wholesale liquidation platform based in Linden, New Jersey, offering brand-name returns and overstock pallets and truckloads at deep discounts for resellers and discount retailers. The company sources inventory from major national retailers and e-commerce platforms, providing a wide selection of manifested merchandise across dozens of categories including electronics, home goods, toys, apparel, health and beauty, tools, and seasonal items. 888 Lots is known for its user-friendly online platform that allows buyers to browse available inventory, view detailed manifests with item descriptions and estimated retail values, and place orders for pickup or delivery. The Linden, New Jersey, location provides excellent logistics access for Northeast buyers, with proximity to major ports, airports, and interstate highways making it convenient for both domestic resellers and international export operations. The company serves bin store operators, Amazon FBA sellers, eBay resellers, flea market vendors, dollar store owners, and wholesale distributors. 888 Lots offers warehouse pickup, LTL freight, and full truckload delivery options.`,

  17: `AAA Closeout Liquidators has been operating since 1979 out of Albany, New York, making it one of the longest-established liquidation companies in the Northeast. The company buys and sells excess inventory, closeouts, and customer returns from major retailers, offering both domestic and international buyers access to pallets and truckloads of general merchandise, electronics, home goods, housewares, apparel, and seasonal products. With over four decades of industry experience, AAA Closeout Liquidators has built deep sourcing relationships that provide consistent access to quality inventory at competitive prices. The Albany location offers cost-effective warehouse space and reasonable freight rates throughout New England, the Mid-Atlantic, and beyond. The company specializes in both manifested and unmanifested lots, with options ranging from small pallet purchases for startup resellers to full truckloads for established wholesale operations. AAA Closeout Liquidators serves discount store owners, bin store operators, Amazon and eBay resellers, flea market vendors, and international export buyers who consolidate shipments from the Northeast corridor for overseas markets.`,

  18: `ALL Wholesale LLC operates from Montebello, California, in the heart of the Los Angeles metro area, serving as a wholesale liquidation supplier of customer returns, overstock, and closeout merchandise. The company sources from major retailers and brand manufacturers, offering a broad selection of pallets and truckloads covering electronics, home goods, health and beauty, apparel, toys, housewares, and general merchandise. ALL Wholesale's proximity to the massive L.A. retail and logistics infrastructure gives it access to some of the highest-volume return streams on the West Coast. The company serves a diverse buyer base including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and international export buyers who use nearby ports for container consolidation. ALL Wholesale offers competitive pricing on both manifested and unmanifested lots, with flexible purchasing options from single pallets to multi-pallet and full truckload orders. Local buyers can arrange warehouse pickup in Montebello, while out-of-state buyers benefit from LTL and full truckload shipping options.`,

  19: `All Prime Products specializes in hardgoods liquidation, sourcing excess inventory from major retailers and offering mixed pallets and truckloads to resellers across the United States. Based in Fairhope, Alabama, the company focuses on high-demand product categories that typically yield strong resale margins, including tools, home improvement products, small appliances, electronics, outdoor equipment, and general merchandise. All Prime Products is known for its selective approach to inventory sourcing, focusing on lots with higher average item values and better condition grades than typical mixed-merchandise pallets. The Alabama location provides competitive freight access throughout the Southeast and Gulf Coast region, with reasonable shipping rates to the Midwest and Southwest as well. The company serves Amazon FBA sellers, eBay resellers, bin store operators, hardware store owners, and discount retailers looking for quality hardgoods inventory at wholesale liquidation prices. All Prime Products offers both manifested and unmanifested lot options, with warehouse pickup available for local buyers and nationwide freight delivery for remote customers.`,

  20: `American Liquidations operates from Waterbury, Connecticut, as a wholesale liquidation supplier offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company carries a broad product mix including electronics, home goods, apparel, toys, health and beauty, tools, housewares, and seasonal merchandise, with new inventory arriving weekly to maintain a fresh selection for regular buyers. American Liquidations' Connecticut location provides convenient access for buyers throughout New England and the greater Northeast, with competitive freight rates for shipping to the Mid-Atlantic, Southeast, and Midwest regions. The company offers both manifested lots with full item visibility and lower-cost unmanifested pallets for experienced buyers comfortable evaluating merchandise on receipt. American Liquidations serves Amazon and eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, consignment shop owners, and discount retail chains. The company provides warehouse pickup for local buyers and arranges LTL and full truckload delivery for customers across the continental United States.`,

  21: `American Pallet Liquidators is a wholesale liquidation company based in Jeffersonville, Indiana, just across the river from Louisville, Kentucky, offering customer returns, overstock, and closeout merchandise from major national retailers. The company provides pallets and truckloads of merchandise across popular categories including electronics, home goods, toys, tools, sporting goods, health and beauty, apparel, and general merchandise. American Pallet Liquidators' location in southern Indiana places it at a strategic crossroads of the Midwest, giving buyers easy access from Ohio, Kentucky, Illinois, Michigan, and surrounding states. The company serves a wide range of resellers including Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, dollar store owners, and discount retail chains. American Pallet Liquidators offers competitive pricing on both manifested and unmanifested lots, with options ranging from single-pallet purchases for new resellers to full truckload orders for high-volume operations. Warehouse pickup is available in Jeffersonville, and nationwide freight delivery is offered with both LTL and full truckload options.`,

  22: `Archer Logistix is a wholesale liquidation and logistics company based in Homer Glen, Illinois, in the greater Chicago metro area, specializing in customer returns, overstock, and closeout merchandise from national retail chains. The company offers pallets and truckloads of inventory across categories including electronics, home goods, health and beauty, tools, toys, apparel, and general merchandise. Archer Logistix combines liquidation sourcing with logistics capabilities, providing integrated solutions for buyers who want their merchandise processed, sorted, or shipped to specific destinations. The Chicago-area location places Archer Logistix at a premier freight hub, with access to major interstate corridors, rail networks, and competitive carrier rates for shipping across the entire continental United States. The company serves Amazon FBA sellers, eBay resellers, bin store operators, Whatnot livestream sellers, discount retail operators, and international export buyers. Archer Logistix offers warehouse pickup for local buyers and nationwide freight delivery including LTL, partial truckload, and full truckload shipments.`,

  23: `AXI Wholesale operates from Ashtabula, Ohio, as a wholesale liquidation supplier offering pallets and truckloads of customer returns, overstock, and shelf-pull merchandise from major U.S. retailers. The company carries a diverse inventory across categories including electronics, home goods, health and beauty, toys, tools, sporting goods, apparel, and general merchandise, with regular inventory replenishment from established retail sourcing partners. AXI Wholesale's northern Ohio location provides cost-effective shipping access throughout the Midwest, Northeast, and Great Lakes regions, making it convenient for buyers from Pennsylvania, New York, Michigan, Indiana, and beyond. The company offers both manifested and unmanifested lot options at competitive price points, allowing buyers to select the product visibility level that matches their business model. AXI Wholesale serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, dollar store owners, and discount retail chains. Warehouse pickup is available in Ashtabula, and freight delivery is offered throughout the continental United States via LTL and full truckload carriers.`,

  24: `Barangle Corporation is a wholesale liquidation company headquartered in Warminster, Pennsylvania, that has established itself as a reliable source for customer returns, overstock, shelf pulls, and closeout merchandise from top U.S. retailers and brand manufacturers. The company operates from a substantial warehouse facility where incoming loads are received, inspected, and organized for resale as pallets and truckloads spanning electronics, home goods, health and beauty, toys, tools, apparel, housewares, and general merchandise. Barangle's Pennsylvania location in the greater Philadelphia corridor provides excellent logistics positioning for buyers throughout the Northeast and Mid-Atlantic regions, with competitive freight rates available nationwide. The company is known for transparent business practices, providing detailed lot descriptions, condition assessments, and estimated retail values for all available inventory. Barangle Corporation serves a broad buyer base including Amazon FBA sellers, eBay resellers, bin store operators, discount store chains, flea market vendors, and international export buyers who consolidate shipments from the Northeast for overseas markets. Warehouse pickup and nationwide freight delivery are both available.`,

  25: `Bin Store Merchandise operates from West Columbia and North Augusta, South Carolina, as a wholesale liquidation supplier specifically designed to serve the growing bin store retail segment. The company sources customer returns, overstock, and shelf-pull merchandise from major retailers and curates inventory into pallet and truckload lots that are optimized for the bin store business model, with emphasis on high item counts, diverse product mixes, and price points that allow store operators to maintain profitable daily markdown schedules. Product categories include electronics, home goods, toys, health and beauty, apparel, housewares, tools, and general merchandise. Bin Store Merchandise understands the unique needs of bin store operators who require consistent weekly inventory deliveries to keep their stores stocked and customers returning. Beyond bin store buyers, the company also serves Amazon and eBay resellers, flea market vendors, discount store operators, and export buyers. Dual South Carolina locations provide convenient pickup options for Southeast buyers and competitive freight access to the East Coast and Midwest regions.`,

  26: `Black Swamp Liquidation is a wholesale liquidation company based in Bowling Green, Ohio, offering pallets and truckloads of customer returns, overstock, and closeout merchandise sourced from major national retailers. The company provides a diverse product selection spanning electronics, home goods, toys, tools, health and beauty, sporting goods, apparel, and general merchandise, with new inventory arriving on a consistent schedule from established retail sourcing channels. Black Swamp Liquidation takes its name from the historic Black Swamp region of northwest Ohio, and the company has built a loyal buyer base throughout the Midwest and Great Lakes area. The Bowling Green location offers competitive freight rates for shipping to Michigan, Indiana, Pennsylvania, West Virginia, and surrounding states. Black Swamp Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot sellers, bin store operators, flea market vendors, discount store owners, and startup resellers looking to enter the liquidation industry. The company offers warehouse pickup for local buyers and arranges LTL and full truckload delivery nationwide.`,

  27: `Boxflipz is a wholesale liquidation company operating from Extension Coraopolis, Pennsylvania, near Pittsburgh, specializing in customer returns and overstock merchandise from major U.S. retailers. The company offers pallets and truckloads of merchandise across a broad category range including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with an emphasis on lots that yield strong returns for resellers who inspect and flip individual items. Boxflipz caters especially to the growing community of Amazon FBA sellers, eBay resellers, and Whatnot livestream sellers who purchase liquidation pallets, sort through the contents, and resell individual items through online marketplaces at significant markups. The western Pennsylvania location provides convenient access for buyers from Pittsburgh, Ohio, West Virginia, and the broader Mid-Atlantic region, with competitive freight rates available for nationwide delivery. Boxflipz offers both manifested and unmanifested pallet options at different price tiers, along with truckload quantities for high-volume buyers. Warehouse pickup and scheduled freight delivery are both available.`,

  28: `Brand Name Bargains, LLC is a wholesale liquidation company based in Brooklyn, New York, that focuses on sourcing high-quality brand-name merchandise from major retailers, department stores, and brand manufacturers for resale to wholesale buyers. The company offers pallets and truckloads of customer returns, overstock, shelf pulls, and closeout inventory spanning designer apparel, shoes, accessories, electronics, home goods, health and beauty products, and general merchandise. Brand Name Bargains differentiates itself through its focus on premium and recognizable brand-name products that command higher resale values than generic mixed-merchandise lots. The Brooklyn location provides exceptional logistics access with proximity to major highways, ports, airports, and the dense population centers of the New York metro area. The company serves boutique retailers, online resellers, consignment shops, bin store operators, flea market vendors, and international export buyers. Brand Name Bargains offers warehouse pickup in Brooklyn and nationwide freight delivery, with lot options ranging from curated single pallets to multi-pallet and full truckload orders for volume buyers.`,

  29: `Bstock is a technology-driven liquidation marketplace headquartered in San Mateo, California, that powers private-label auction platforms for some of the largest retailers in the world. The company's proprietary marketplace technology enables retailers to sell customer returns, overstock, and excess inventory directly to vetted wholesale buyers through competitive online auctions. Bstock operates distinct marketplace storefronts for individual retailers, giving buyers access to manifested lots with clear sourcing provenance and condition details. Product categories span the full retail spectrum including consumer electronics, home goods, apparel, health and beauty, toys, tools, and specialty merchandise. Lot sizes range from single pallets to multi-truckload quantities, with pricing determined through real-time auction bidding. Bstock serves a global buyer community including Amazon FBA sellers, eBay resellers, discount retail chains, bin store operators, secondary market distributors, and international export buyers. The company's multiple warehouse locations across the United States provide regional pickup options and competitive freight rates, while its technology platform offers real-time bidding, manifest downloads, and shipment tracking.`,

  30: `COHO Liquidation operates from Sedro-Woolley, Washington, in the Pacific Northwest, as a wholesale liquidation supplier offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company carries a wide product selection across categories including electronics, home goods, toys, outdoor equipment, tools, health and beauty, apparel, and general merchandise, with particular strength in categories popular in the Pacific Northwest market. COHO Liquidation's Washington State location makes it an accessible source for buyers throughout the Pacific Northwest, including the Seattle and Portland metro areas, while also serving buyers in Northern California, Idaho, Montana, and Alaska. The company offers both manifested and unmanifested lot options, with competitive pricing that attracts both new and experienced liquidation buyers. COHO Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and discount store operators. Warehouse pickup is available in Sedro-Woolley, and freight delivery is offered throughout the western United States and beyond.`,

  31: `Comprehensive Liquidation is a wholesale liquidation company headquartered in Los Angeles, California, specializing in customer returns, overstock, shelf pulls, and closeout merchandise from leading U.S. retailers and brand manufacturers. The company operates from a large warehouse facility that enables high-volume inventory processing, sorting, and distribution of pallets and truckloads covering electronics, home goods, health and beauty, apparel, toys, tools, housewares, and general merchandise. Comprehensive Liquidation is known for its thorough approach to lot preparation, providing buyers with detailed manifests, condition reports, and estimated retail values that help evaluate potential profit margins before purchasing. The Los Angeles location places the company at the heart of one of the largest liquidation markets in the country, with access to enormous retail return volumes from major fulfillment centers and distribution hubs across Southern California. The company serves Amazon FBA sellers, eBay resellers, bin store operators, discount retailers, flea market vendors, and international export buyers who leverage proximity to the Port of Long Beach for ocean freight consolidation.`,

  32: `Continental Wholesale operates from Hampton, Iowa, as a wholesale liquidation supplier offering pallets and truckloads of customer returns, overstock, and closeout merchandise sourced from major U.S. retailers and manufacturers. The company provides a diverse product selection covering electronics, home goods, tools, health and beauty, toys, sporting goods, seasonal merchandise, and general merchandise, with regular inventory turnover from established sourcing relationships. Continental Wholesale's central Iowa location provides exceptional freight positioning for shipping anywhere in the continental United States, with competitive carrier rates to both coasts and all major metro areas. The company is known for its straightforward pricing and honest condition descriptions, building trust with repeat buyers who depend on consistent inventory quality. Continental Wholesale serves Amazon FBA sellers, eBay resellers, Whatnot sellers, bin store operators, flea market vendors, discount store chains, and rural retailers looking for affordable merchandise at wholesale liquidation prices. The company offers warehouse pickup for Midwest buyers and arranges nationwide freight delivery via LTL and full truckload carriers.`,

  33: `Discount Truckloads operates from Dallas, Texas, as a wholesale liquidation company specializing in full truckload and pallet-level sales of customer returns, overstock, and closeout merchandise from major national retailers. True to its name, the company focuses on high-volume truckload deals that offer buyers the deepest per-unit pricing available in the liquidation market. Product categories include electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, with loads sourced from some of the largest retail return processing centers in the country. The Dallas location sits at a major freight crossroads in the South Central United States, providing competitive shipping rates throughout Texas, the Southeast, Midwest, and Southwest. Discount Truckloads serves established resellers and wholesale operations that have the warehouse space and sales channels to handle large-volume purchases, including Amazon FBA sellers, eBay power sellers, bin store chains, discount retail operations, and international export buyers. The company offers warehouse pickup in Dallas and arranges nationwide freight delivery for truckload and LTL shipments.`,

  34: `East Coast Liquidators is a wholesale liquidation company based in Vero Beach, Florida, specializing in customer returns, overstock, shelf pulls, and closeout merchandise from major retailers and brand manufacturers. The company offers pallets and truckloads across popular categories including electronics, home goods, toys, health and beauty, apparel, tools, outdoor equipment, and general merchandise. East Coast Liquidators has built a reputation for consistent inventory quality and transparent business practices, providing detailed lot descriptions and condition assessments that help buyers evaluate potential returns before purchasing. The Vero Beach location on Florida's east coast provides convenient access for buyers throughout the Southeast, with proximity to ports in Miami, Fort Lauderdale, and Jacksonville enabling cost-effective export shipping to the Caribbean, Latin America, and other international markets. The company serves Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, discount retailers, and wholesale export buyers. East Coast Liquidators offers warehouse pickup for local buyers and nationwide freight delivery with both LTL and full truckload options.`,

  35: `Excess4Less operates from Washington State as a wholesale liquidation supplier focused on delivering customer returns, overstock, and closeout merchandise from major U.S. retailers at competitive prices. The company offers pallets and truckloads across a diverse range of categories including electronics, home improvement, outdoor equipment, tools, toys, health and beauty, housewares, and general merchandise, with particular emphasis on product categories that perform well in the Pacific Northwest market. Excess4Less serves both local Washington buyers and customers across the western United States, taking advantage of Pacific Northwest logistics corridors for competitive freight rates to California, Oregon, Idaho, and surrounding states. The company offers manifested and unmanifested lot options at different price tiers, giving buyers the flexibility to choose lots that match their risk tolerance and business model. Excess4Less serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and discount store owners looking for quality liquidation inventory at wholesale prices. Warehouse pickup and freight delivery are both available.`,

  36: `Freedom Wholesale is a liquidation and wholesale company based in Fishers, Indiana, in the greater Indianapolis metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers. The company provides inventory across popular product categories including electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, with regular restocking from established retail sourcing partnerships. Freedom Wholesale's central Indiana location provides excellent logistics positioning at the crossroads of the Midwest, with competitive freight rates available for shipping to Ohio, Michigan, Illinois, Kentucky, and throughout the eastern half of the United States. The company is known for fair pricing and transparent lot descriptions that help buyers calculate potential margins before committing to a purchase. Freedom Wholesale serves Amazon FBA sellers, eBay resellers, Whatnot sellers, bin store operators, flea market vendors, discount retail chains, and startup resellers entering the liquidation business. Warehouse pickup is available in Fishers, and the company arranges nationwide freight delivery via LTL and full truckload carriers.`,

  37: `GRP Liquidations is a wholesale liquidation company based in South Grand Rapids, Michigan, offering pallets and truckloads of customer returns, overstock, and closeout merchandise sourced from major U.S. retailers and e-commerce platforms. The company provides a wide selection of merchandise across popular categories including electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, outdoor equipment, and general merchandise. GRP Liquidations' Michigan location serves as a strategic hub for buyers throughout the Great Lakes region, including Michigan, Ohio, Indiana, Illinois, Wisconsin, and surrounding states, with competitive freight rates available nationwide. The company maintains consistent inventory flow from established sourcing relationships, ensuring that repeat buyers always have access to fresh loads. GRP Liquidations serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and international export buyers. The company offers both manifested and unmanifested lot options, with warehouse pickup available in Grand Rapids and freight delivery arranged throughout the continental United States.`,

  38: `HJ Liquidators Closeouts is a wholesale liquidation company based in Franklin Park, Illinois, in the greater Chicago metro area, offering pallets and truckloads of closeout merchandise, customer returns, and overstock inventory from major national retailers and brand manufacturers. The company carries a broad product mix spanning electronics, home goods, tools, health and beauty, toys, apparel, housewares, and general merchandise, with strong expertise in closeout deals that provide buyers with brand-new merchandise at deep discounts below traditional wholesale cost. HJ Liquidators' Franklin Park location places it in one of the premier logistics corridors in the United States, with access to major highways, rail hubs, and competitive carrier rates for shipping nationwide. The company has built long-standing relationships with retailers and manufacturers that ensure consistent access to quality closeout and excess inventory. HJ Liquidators serves discount store chains, bin store operators, Amazon and eBay resellers, flea market vendors, dollar store owners, and international export buyers. Warehouse pickup and nationwide freight delivery are available.`,

  39: `Ice Liquidation is a wholesale liquidation supplier based in Pompano Beach, Florida, specializing in customer returns, overstock, and closeout merchandise from major U.S. retailers and e-commerce platforms. The company offers pallets and truckloads of merchandise across popular categories including electronics, home goods, health and beauty, toys, tools, apparel, and general merchandise, with regular inventory turnover from established sourcing partnerships. Ice Liquidation's South Florida location provides convenient access for buyers throughout Florida and the Southeast, while also serving as a natural hub for international export buyers shipping through the Port of Miami, Port Everglades, and other regional ports. The company is known for competitive pricing and responsive customer service, building a loyal repeat buyer base that includes Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount retailers, and wholesale export operations. Ice Liquidation offers both manifested and unmanifested lot options, with warehouse pickup available in Pompano Beach and freight delivery offered throughout the continental United States.`,

  40: `IDX Liquidations is a wholesale liquidation company based in Maspeth, New York, in the Queens borough of New York City, specializing in customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company offers pallets and truckloads across diverse product categories including electronics, home goods, health and beauty, apparel, toys, housewares, designer goods, and general merchandise. IDX Liquidations' New York City location provides unmatched access to one of the densest retail and logistics markets in the country, with proximity to multiple ports, airports, and the extensive tri-state freight network. The company is well-positioned to serve both domestic resellers throughout the Northeast and international export buyers who consolidate shipments from the New York metro area for overseas distribution. IDX Liquidations serves Amazon FBA sellers, eBay resellers, bin store operators, boutique retailers, consignment shop owners, flea market vendors, and large-scale wholesale export operations. The company offers warehouse pickup in Maspeth and arranges freight delivery nationwide via LTL and full truckload carriers.`,

  41: `J&M Liquidation LLC is a wholesale liquidation company based in Myrtle Beach, South Carolina, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company provides a diverse inventory covering electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, with new loads arriving regularly from established sourcing channels. J&M Liquidation has carved out a strong presence in the Southeast liquidation market, serving buyers along the Carolina coast and throughout the Southeast region with competitive pricing and consistent product quality. The Myrtle Beach location provides convenient warehouse access for local buyers and affordable freight rates throughout the eastern United States. J&M Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and vacation-area retail shops looking for affordable merchandise. The company offers manifested and unmanifested lot options at various price points, with warehouse pickup and scheduled freight delivery available for all order sizes.`,

  42: `Keystone Liquidators operates from Seven Valleys, Pennsylvania, as a wholesale liquidation company offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. Named after Pennsylvania's Keystone State nickname, the company provides a wide product selection across categories including electronics, home goods, toys, tools, health and beauty, apparel, housewares, and general merchandise. Keystone Liquidators has built a reputation for honest lot descriptions, consistent inventory quality, and competitive pricing that attracts repeat buyers from across the Mid-Atlantic and Northeast regions. The Seven Valleys location in south-central Pennsylvania provides excellent logistics access with proximity to major highways connecting to Baltimore, Philadelphia, New York, and Washington, D.C. The company offers both manifested and unmanifested lot options at different price tiers, accommodating both new resellers testing the market and established operations purchasing in volume. Keystone Liquidators serves Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, discount retailers, and wholesale distributors. Warehouse pickup and nationwide freight delivery are available.`,

  43: `LiquidateNow is an online wholesale liquidation marketplace that connects buyers with pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers across the United States. The platform operates as a technology-driven marketplace where multiple suppliers list their available inventory, giving buyers the ability to compare lots, prices, and condition grades across different sources in a single shopping experience. Product categories available on LiquidateNow span the full retail spectrum including electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise. The platform serves buyers nationwide, with shipping coordinated from supplier warehouse locations across multiple states. LiquidateNow caters to a diverse buyer community including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and international export buyers. The marketplace offers both auction-style and fixed-price purchasing options, with lot sizes ranging from single pallets for startup resellers to multi-truckload quantities for high-volume wholesale operations.`,

  44: `Liquidation Brokers LLC is a wholesale liquidation brokerage based in Warren, Ohio, that connects buyers with customer returns, overstock, and closeout merchandise from major national retailers and brand manufacturers. As a broker, the company leverages its network of retail sourcing relationships to match buyers with the specific types of merchandise, lot sizes, and price points that fit their business needs. Product categories include electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, available in both pallet and truckload quantities. Liquidation Brokers' Ohio location provides central positioning in the Midwest with competitive freight access to Pennsylvania, Michigan, Indiana, New York, and the broader eastern United States. The company specializes in helping both new and experienced buyers navigate the liquidation market, providing guidance on lot selection, condition expectations, and logistics planning. Liquidation Brokers serves Amazon FBA sellers, eBay resellers, bin store operators, Whatnot sellers, flea market vendors, discount retailers, and startup resellers looking for a trusted sourcing partner.`,

  45: `Liquidation Closeouts is a wholesale liquidation supplier based in Hudson, Florida, offering pallets and truckloads of customer returns, overstock, shelf pulls, and closeout merchandise from major retailers across the United States. The company provides a diverse product selection spanning electronics, home goods, toys, health and beauty, tools, apparel, seasonal items, and general merchandise, with a focus on lots that deliver strong value for resellers at competitive wholesale prices. Liquidation Closeouts' location on Florida's Gulf Coast provides convenient access for buyers throughout Florida, the Southeast, and the Gulf Coast region, while also serving as a logistics-friendly location for international export buyers working with Gulf port facilities. The company is known for honest condition assessments and responsive communication that helps buyers make informed purchasing decisions. Liquidation Closeouts serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, dollar store owners, and discount retail chains. Warehouse pickup is available in Hudson, and the company arranges LTL and full truckload delivery nationwide.`,

  46: `Liquidation Deals Canada is a wholesale liquidation company based in North York, Ontario, serving as one of Canada's leading sources for customer returns, overstock, and closeout merchandise from major North American retailers. The company offers pallets and truckloads of inventory spanning electronics, home goods, toys, health and beauty, apparel, housewares, tools, and general merchandise, sourced from both Canadian and American retail chains. Liquidation Deals Canada fills a critical niche for Canadian resellers who face limited options compared to the vast U.S. liquidation market, providing domestic sourcing that avoids the complexities of cross-border customs, duties, and brokerage fees. The North York location in the Greater Toronto Area provides convenient access for Ontario-based buyers and cost-effective freight to provinces across Canada. The company serves Amazon.ca sellers, eBay Canada resellers, bin store operators, flea market vendors, discount store owners, and wholesale distributors throughout English and French-speaking Canada. Both warehouse pickup and nationwide Canadian freight delivery are available for all lot sizes.`,

  47: `Liquidators USA is a wholesale liquidation company based in Peachtree City, Georgia, just south of Atlanta, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers and e-commerce platforms. The company provides a wide selection of merchandise across categories including electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, with regular inventory replenishment from established retail sourcing channels. Liquidators USA's Peachtree City location provides excellent logistics access in the Atlanta metro area, one of the largest freight hubs in the Southeast, with competitive carrier rates for shipping throughout the eastern United States and beyond. The company has built a loyal repeat buyer base through consistent inventory quality, fair pricing, and transparent lot descriptions that include condition assessments and estimated retail values. Liquidators USA serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and international export buyers. Warehouse pickup and nationwide freight delivery are both available.`,

  48: `LiquidityApp is a technology-driven wholesale liquidation platform based in Missouri City, Texas, in the greater Houston metro area, that connects buyers with pallets and truckloads of customer returns, overstock, and closeout merchandise through an intuitive mobile and web application. The platform sources inventory from major retailers and brand manufacturers, offering a wide selection of merchandise across categories including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise. LiquidityApp differentiates itself through its technology-first approach, providing buyers with a streamlined digital experience for browsing inventory, viewing manifests, placing orders, and tracking shipments from their phones or computers. The Houston-area location provides excellent freight positioning for buyers throughout Texas, the Southeast, and the South Central United States. LiquidityApp serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and discount store owners. The platform offers both manifested and unmanifested lot options at various price points, with warehouse pickup available locally and freight delivery arranged nationwide.`,

  49: `Live Wire Liquidators is a wholesale liquidation company based in Lancaster, Ohio, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers. The company provides a diverse inventory spanning electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, outdoor equipment, and general merchandise, with consistent inventory flow from established sourcing relationships with retail return processing centers. Live Wire Liquidators' central Ohio location offers strategic positioning for buyers throughout the Midwest, Great Lakes, and Appalachian regions, with competitive freight rates to Pennsylvania, Michigan, Indiana, West Virginia, and the broader eastern United States. The company has earned a reputation for fair dealing and transparent lot descriptions, building a loyal base of repeat buyers who depend on consistent quality and pricing. Live Wire Liquidators serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and startup resellers. Warehouse pickup is available in Lancaster, and nationwide freight delivery is offered via LTL and full truckload carriers.`,

  50: `Marketplace Closeouts operates from Denver, Colorado, as a wholesale liquidation company offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company provides inventory across popular categories including electronics, home goods, outdoor and sporting equipment, tools, health and beauty, apparel, toys, and general merchandise, with particular strength in outdoor and recreation products that are popular in the Rocky Mountain market. Marketplace Closeouts' Denver location provides a unique logistics advantage, sitting at the geographic center of the western United States with competitive freight access to both the West Coast and the central plains states. The company serves a broad buyer base including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and outdoor recreation retailers looking for affordable branded inventory. Marketplace Closeouts offers both manifested and unmanifested lot options at different price tiers, with warehouse pickup available in Denver and nationwide freight delivery arranged through LTL and full truckload carriers.`,

  51: `Marketplace Liquidation is a wholesale liquidation company based in Brooklyn Center, Minnesota, in the Minneapolis-Saint Paul metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers. The company provides a diverse product selection spanning electronics, home goods, toys, tools, health and beauty, apparel, seasonal items, and general merchandise, with regular inventory turnover from established retail sourcing channels that keep fresh loads available for repeat buyers. Marketplace Liquidation's Twin Cities location provides excellent freight positioning in the Upper Midwest, with competitive carrier rates for shipping to Wisconsin, Iowa, the Dakotas, Michigan, and the broader central United States. The company has built a strong reputation for honest condition descriptions, consistent lot quality, and responsive customer service that makes it a preferred supplier for both experienced liquidation buyers and newcomers to the industry. Marketplace Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot sellers, bin store operators, flea market vendors, and discount retail chains. Warehouse pickup and nationwide delivery are available.`,

  52: `Midtown Liquidation is a wholesale liquidation supplier based in Menifee, California, in the Inland Empire region of Southern California, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers. The company provides inventory across a wide range of categories including electronics, home goods, health and beauty, toys, tools, apparel, housewares, outdoor equipment, and general merchandise, sourced from some of the largest retail return processing centers in the western United States. Midtown Liquidation's Inland Empire location places it in one of the highest-volume logistics corridors in the country, with proximity to major distribution centers, fulfillment warehouses, and the ports of Long Beach and Los Angeles. The company serves a diverse buyer base including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount retailers, and international export buyers who consolidate container loads for overseas shipment from Southern California. Midtown Liquidation offers competitive pricing on both manifested and unmanifested lots, with warehouse pickup and freight delivery options available.`,

  53: `Orotex Liquidation is a wholesale liquidation company based in Hialeah, Florida, specializing in customer returns, overstock, and closeout merchandise from major U.S. retailers and brand manufacturers. The company operates a substantial warehouse facility where incoming inventory is received, processed, and prepared for resale as pallets and truckloads spanning electronics, home goods, health and beauty, toys, tools, apparel, housewares, and general merchandise. Orotex Liquidation is well-known in the South Florida liquidation market for its competitive pricing, high-volume inventory availability, and strong relationships with international export buyers who ship containers from South Florida ports to Latin America, the Caribbean, Africa, and other global destinations. The company also serves domestic buyers including Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, and discount retail chains throughout the Southeast and beyond. Orotex Liquidation's Hialeah location provides convenient access to Miami-Dade County's extensive logistics infrastructure, including port facilities, freight forwarders, and container consolidation services. Warehouse pickup and nationwide freight delivery are available.`,

  54: `Premier Liquidation is a wholesale liquidation company based in Canton, Ohio, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company carries a wide product selection across categories including electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, with consistent inventory availability from established sourcing relationships. Premier Liquidation's Canton location in northeast Ohio provides excellent logistics positioning for buyers throughout the Midwest and Northeast, with competitive freight rates available to Pennsylvania, New York, Michigan, Indiana, West Virginia, and the broader eastern United States. The company has built a reputation for quality inventory selection, honest condition reporting, and competitive pricing that attracts both experienced liquidation buyers and newcomers entering the resale business. Premier Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and wholesale distributors. Warehouse pickup is available in Canton, and the company arranges nationwide freight delivery via LTL and full truckload carriers.`,

  55: `Premier Wholesaler is a wholesale liquidation and distribution company based in Miami, Florida, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company specializes in serving both domestic resellers and international export buyers, leveraging its Miami location at the crossroads of North American, Caribbean, and Latin American trade. Product categories include electronics, home goods, health and beauty, toys, tools, apparel, housewares, and general merchandise, with particular expertise in curating lots for the export market that comply with destination country import requirements. Premier Wholesaler's proximity to the Port of Miami, PortMiami, and Miami International Airport makes it exceptionally convenient for buyers consolidating ocean and air freight shipments for international destinations. The company serves Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, discount retailers, and wholesale export operations throughout the Americas, Africa, and the Middle East. Warehouse pickup and domestic freight delivery are available alongside international logistics coordination.`,

  56: `Quantum Commodities is a wholesale liquidation and surplus merchandise company that specializes in connecting buyers with customer returns, overstock, and closeout inventory from major U.S. retailers and brand manufacturers. The company operates across multiple channels, offering pallets and truckloads of merchandise spanning electronics, home goods, health and beauty, apparel, toys, tools, and general merchandise. Quantum Commodities takes a data-driven approach to inventory sourcing and pricing, analyzing market conditions, category trends, and buyer demand to ensure competitive pricing and relevant product selections. The company serves a national buyer base including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store chains, and international export buyers. Quantum Commodities offers flexible lot configurations from single pallets for small-volume buyers to multi-truckload packages for large wholesale operations, with detailed manifests and condition reports provided for all available inventory. The company arranges warehouse pickup and nationwide freight delivery, working with preferred carrier partners to secure competitive shipping rates for buyers across the country.`,

  57: `RDW Liquidation operates from Rome, Georgia, as a wholesale liquidation company offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company provides inventory across diverse product categories including electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, with regular loads arriving from established retail sourcing partnerships. RDW Liquidation's northwest Georgia location sits along the I-75 corridor between Atlanta and Chattanooga, providing excellent freight access throughout the Southeast and competitive shipping rates to the Midwest and East Coast. The company is known for consistent inventory quality and honest lot descriptions that help buyers accurately assess potential margins before committing to a purchase. RDW Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and startup resellers looking for a reliable Southeast sourcing partner. Warehouse pickup is available in Rome, and the company arranges LTL and full truckload delivery nationwide.`,

  58: `REMEX Liquidation Wholesale, Export, Overstock Sales is a wholesale liquidation and export company based in Dallas, Texas, that specializes in large-volume sales of customer returns, overstock, and closeout merchandise for both domestic and international buyers. As its name suggests, REMEX focuses on three core business lines: liquidation purchasing for domestic resellers, wholesale distribution, and export operations serving international markets across Latin America, Africa, the Caribbean, and beyond. The company offers pallets and truckloads of merchandise spanning electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with particular expertise in assembling mixed-category container loads optimized for export market demand. REMEX's Dallas location provides central U.S. freight positioning and proximity to major international shipping corridors, making it efficient for both domestic and export fulfillment. The company serves discount retailers, bin store operators, Amazon and eBay resellers, international distributors, and wholesale export buyers who need consistent high-volume inventory at deep discounts. Warehouse pickup and nationwide freight delivery are available.`,

  59: `RMW Liquidations is a wholesale liquidation company based in Shelbyville, Indiana, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers. The company provides a broad product selection spanning electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, with regular inventory replenishment from established retail sourcing channels. RMW Liquidations' central Indiana location provides outstanding logistics positioning in the heart of the Midwest, with competitive freight rates to Ohio, Michigan, Illinois, Kentucky, and the broader eastern United States. The company has developed efficient warehouse operations that enable quick turnaround on incoming loads, keeping fresh inventory available for buyers who purchase on a regular schedule. RMW Liquidations serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and wholesale distributors looking for reliable Midwest sourcing. The company offers manifested and unmanifested lot options at competitive price points, with warehouse pickup in Shelbyville and nationwide freight delivery available.`,

  60: `Salvage Closeouts, Inc. is a wholesale liquidation company based in Elizabeth, New Jersey, that has established itself as a prominent supplier of customer returns, overstock, salvage, and closeout merchandise from major retailers and manufacturers. The company's Elizabeth location sits within one of the densest logistics corridors in the United States, adjacent to the Port of New York and Newark, Newark Liberty Airport, and major highway networks. Salvage Closeouts offers pallets and truckloads across broad product categories including electronics, home goods, health and beauty, apparel, toys, housewares, tools, and general merchandise, with competitive pricing that reflects its high-volume sourcing capabilities and efficient warehouse operations. The company serves a diverse buyer base including domestic resellers, discount store chains, bin store operators, Amazon and eBay sellers, flea market vendors, and international export buyers who take advantage of the proximity to the port for container consolidation and overseas shipping. Salvage Closeouts provides both manifested and unmanifested lot options, with warehouse pickup available in Elizabeth and freight delivery arranged nationwide.`,

  61: `ShowMe Liquidation is a wholesale liquidation company based in Aurora, Missouri, serving as a reliable source for customer returns, overstock, and closeout merchandise from major national retailers. The company offers pallets and truckloads of inventory across popular product categories including electronics, home goods, toys, tools, health and beauty, apparel, seasonal merchandise, and general merchandise, with a focus on delivering consistent value at competitive wholesale liquidation prices. ShowMe Liquidation's southwest Missouri location provides a cost-effective base for serving buyers throughout the Midwest, Ozarks region, and the South Central United States, with reasonable freight rates to Kansas, Oklahoma, Arkansas, and surrounding states. The company has built a following among buyers who appreciate its straightforward approach to business, including honest condition descriptions and fair pricing. ShowMe Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and small-town retailers looking for affordable inventory. Warehouse pickup is available in Aurora, and the company arranges LTL and full truckload delivery nationwide.`,

  62: `Smart Source Wholesale is a wholesale liquidation and distribution company based in Houston, Texas, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers and brand manufacturers. The company handles a diverse product mix spanning electronics, home goods, health and beauty, toys, tools, apparel, housewares, and general merchandise, sourced from some of the largest retail return processing operations in Texas and the Gulf Coast region. Smart Source Wholesale's Houston location provides excellent logistics access through one of the busiest freight corridors in the country, with competitive shipping rates throughout the South, Southwest, and Midwest. The company is known for its organized warehouse operations and reliable inventory flow, maintaining consistent availability of fresh loads for repeat buyers who purchase on regular schedules. Smart Source Wholesale serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store chains, and international export buyers. Warehouse pickup is available in Houston, and the company arranges nationwide freight delivery via LTL and full truckload carriers.`,

  63: `SmartLots is a wholesale liquidation company based in Winston-Salem, North Carolina, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company provides a wide selection of merchandise across categories including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with a technology-forward approach to inventory management and buyer communication. SmartLots' Winston-Salem location provides strategic positioning in the Piedmont Triad region of North Carolina, with excellent freight access to the Southeast, Mid-Atlantic, and Northeast markets via I-40 and I-85. The company has invested in systems that provide buyers with detailed manifest data, condition assessments, and estimated retail values for all available inventory, enabling more informed purchasing decisions. SmartLots serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and wholesale distributors throughout the United States. Warehouse pickup and nationwide freight delivery are both available for pallet and truckload orders.`,

  64: `Southern Liquidation is a wholesale liquidation company based in Siloam Springs, Arkansas, near the headquarters of major retail chains, specializing in customer returns, overstock, and closeout merchandise from top national retailers. The company's northwestern Arkansas location provides direct access to one of the largest concentrations of retail headquarters and distribution centers in the country, giving Southern Liquidation privileged sourcing access to high-quality return streams. Product categories include electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, available in both pallet and truckload quantities. Southern Liquidation leverages its proximity to retail distribution networks to offer competitive pricing and fresh inventory on a consistent basis. The company serves a diverse buyer base including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount retailers, and wholesale distributors throughout the central United States. Warehouse pickup is available in Siloam Springs, and nationwide freight delivery is offered through LTL and full truckload carriers.`,

  65: `Streamline Liquidations is a wholesale liquidation company based in Hope Mills, North Carolina, near the Fayetteville metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company provides inventory across a diverse range of categories including electronics, home goods, toys, tools, health and beauty, apparel, sporting goods, and general merchandise, with regular restocking from established retail sourcing partnerships. Streamline Liquidations has built its business on efficient warehouse operations and reliable inventory processing, ensuring that buyers receive accurately described lots on consistent timelines. The Hope Mills location provides competitive freight access throughout the Southeast and Mid-Atlantic regions, with I-95 proximity enabling cost-effective shipping to markets from Florida to New England. Streamline Liquidations serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and wholesale distributors. The company offers manifested and unmanifested lot options at various price points, with warehouse pickup available locally and nationwide freight delivery arranged for all order sizes.`,

  66: `Supreme Liquidator is a wholesale liquidation company based in Warminster, Pennsylvania, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company has built expertise in sourcing high-value and brand-name merchandise that commands premium resale prices, focusing on categories including electronics, designer apparel, shoes, health and beauty, home goods, housewares, and general merchandise. Supreme Liquidator's Warminster location in the greater Philadelphia corridor provides excellent logistics positioning for buyers throughout the Northeast and Mid-Atlantic, with proximity to major highways, ports, and freight terminals that enable competitive shipping rates nationwide. The company differentiates itself through careful lot curation that focuses on higher-value items and better condition grades than typical bulk liquidation offerings. Supreme Liquidator serves Amazon FBA sellers, eBay resellers, boutique retailers, consignment shop owners, bin store operators, flea market vendors, and international export buyers. Warehouse pickup is available in Warminster, and the company arranges nationwide freight delivery for all pallet and truckload orders.`,

  67: `That Liquidation Place is a wholesale liquidation company based in York, Pennsylvania, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers. The company provides a diverse product selection spanning electronics, home goods, toys, tools, health and beauty, apparel, housewares, and general merchandise, with regular inventory arrivals from established retail sourcing channels. That Liquidation Place has cultivated a welcoming reputation in the liquidation community, particularly among newer buyers who appreciate the company's willingness to answer questions and provide guidance on lot selection. The York, Pennsylvania, location provides central positioning between Philadelphia, Baltimore, and Harrisburg, with competitive freight access throughout the Mid-Atlantic, Northeast, and Southeast regions. That Liquidation Place serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and startup resellers entering the liquidation business for the first time. Warehouse pickup is available in York, and nationwide freight delivery is arranged through LTL and full truckload carriers.`,

  68: `The Discount Warehouse, commonly known as TDW, is a wholesale liquidation company based in Sunrise, Florida, in the greater Fort Lauderdale metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company operates from a large warehouse facility where incoming loads are processed, organized, and made available to buyers across categories including electronics, home goods, health and beauty, toys, tools, apparel, housewares, and general merchandise. TDW's South Florida location provides convenient access for both domestic buyers throughout the Southeast and international export buyers who utilize nearby port facilities in Fort Lauderdale and Miami for container shipping to the Caribbean, Latin America, and other global markets. The company maintains a diverse buyer base that includes Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, discount retail chains, dollar store operators, and wholesale export businesses. TDW offers competitive pricing on both manifested and unmanifested lots, with warehouse pickup available in Sunrise and freight delivery arranged nationwide.`,

  69: `The Select Source is a wholesale liquidation company based in Haslet, Texas, in the Dallas-Fort Worth metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company provides a carefully curated inventory selection across categories including electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, with an emphasis on lots that have been vetted for quality and resale potential. The Select Source differentiates itself through its selective approach to inventory sourcing, prioritizing lots with higher average item values and better condition profiles than typical bulk liquidation offerings. The Haslet location provides excellent logistics access in the Dallas-Fort Worth metroplex, one of the largest freight hubs in the South Central United States, with competitive carrier rates available nationwide. The Select Source serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, and discount retailers. Warehouse pickup and nationwide freight delivery are both available for all order sizes.`,

  70: `Trends Liquidation is a wholesale liquidation company based in Houston, Texas, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company focuses on trending product categories and fast-moving consumer goods that resellers can turn quickly for profit, including electronics, home goods, health and beauty, toys, apparel, tech accessories, and general merchandise. Trends Liquidation's Houston location provides excellent logistics positioning in one of the largest metro areas and freight hubs in the United States, with competitive shipping rates throughout Texas, the Southeast, Southwest, and Midwest. The company monitors market trends and buyer demand to source inventory that aligns with what resellers are currently selling, helping buyers avoid stale or slow-moving merchandise. Trends Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, and online marketplace sellers looking for in-demand merchandise at wholesale liquidation prices. Warehouse pickup is available in Houston, and nationwide freight delivery is offered via LTL and full truckload carriers.`,

  71: `Orotex Liquidations is a wholesale liquidation supplier based in Hialeah, Florida, specializing in customer returns, overstock, and closeout merchandise from major U.S. retailers and brand manufacturers. The company offers pallets and truckloads of inventory across categories including electronics, home goods, health and beauty, toys, tools, apparel, and general merchandise, with a strong focus on high-volume sales to both domestic resellers and international export buyers. Orotex Liquidations' Hialeah location in Miami-Dade County provides unmatched access to South Florida's extensive international trade infrastructure, including the Port of Miami, Port Everglades, and multiple freight forwarding and container consolidation services. The company has deep expertise in preparing and documenting export loads that meet the requirements of destination countries across Latin America, the Caribbean, Africa, and other emerging markets. Orotex Liquidations also serves domestic buyers including Amazon FBA sellers, eBay resellers, bin store operators, flea market vendors, and discount retail chains. Warehouse pickup and both domestic and international shipping coordination are available.`,

  72: `TruckloadDeals.com is an online wholesale liquidation marketplace connecting buyers with full truckloads and pallets of customer returns, overstock, and closeout merchandise from major retailers across the United States. The platform operates as a digital-first marketplace where buyers can browse available inventory, review lot details and manifests, and purchase directly through the website without the complexity of in-person auctions or negotiations. Product categories span the full retail spectrum including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with new loads posted regularly from multiple sourcing partners. TruckloadDeals.com serves a national buyer base, with merchandise shipped from supplier warehouses in various locations to keep freight costs competitive regardless of the buyer's location. The platform caters to Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store chains, and high-volume wholesale operations. TruckloadDeals.com offers both manifested and unmanifested lot options at various price points, with flexible shipping arrangements coordinated through the platform.`,

  73: `Unboxed Wholesale, LLC is a wholesale liquidation company based in Lebanon, Ohio, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major national retailers and e-commerce platforms. The company specializes in unboxed and open-box merchandise that has been returned by customers but remains in good functional condition, providing resellers with inventory that typically commands higher resale values than typical mixed-condition liquidation lots. Product categories include electronics, home goods, tools, health and beauty, toys, outdoor equipment, and general merchandise. Unboxed Wholesale's Lebanon, Ohio, location provides excellent Midwest logistics access, with competitive freight rates to Indiana, Michigan, Pennsylvania, Kentucky, and the broader eastern United States. The company has built its reputation on thorough condition assessment and honest lot descriptions that allow buyers to accurately predict their resale margins. Unboxed Wholesale serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, and refurbishment operations. Warehouse pickup and nationwide freight delivery are available.`,

  74: `Up Liquidation is a wholesale liquidation company operating in North Carolina, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers. The company provides a diverse product selection across categories including electronics, home goods, toys, tools, health and beauty, apparel, and general merchandise, with regular inventory arrivals from established retail sourcing channels that ensure fresh loads are consistently available. Up Liquidation has built a growing presence in the Southeast liquidation market, serving buyers who value competitive pricing, honest condition descriptions, and reliable inventory availability. The North Carolina location provides strategic logistics access throughout the eastern United States, with competitive freight rates to neighboring states and the broader Southeast, Mid-Atlantic, and Northeast regions. Up Liquidation serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and startup resellers looking for an accessible entry point into the liquidation industry. The company offers warehouse pickup for local buyers and arranges LTL and full truckload delivery nationwide.`,

  75: `What a Bargain is a wholesale liquidation supplier based in Amsterdam, New York, offering pallets and truckloads of customer returns, overstock, shelf pulls, and closeout merchandise from major retailers and brand manufacturers. The company provides a wide selection of inventory across product categories including electronics, home goods, health and beauty, toys, tools, apparel, housewares, seasonal items, and general merchandise. What a Bargain's upstate New York location provides convenient access for buyers throughout New York State, New England, and the broader Northeast, with competitive freight rates available for shipping to the Mid-Atlantic, Southeast, and Midwest regions. The company serves a diverse buyer base that includes Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store operators, dollar store owners, and rural retailers looking for affordable merchandise at deep discounts below wholesale cost. What a Bargain offers both manifested and unmanifested lot options, with warehouse pickup available in Amsterdam and nationwide freight delivery arranged through LTL and full truckload carriers.`,

  76: `Wholesale Truckload Liquidators is a wholesale liquidation company focused on full truckload sales of customer returns, overstock, and closeout merchandise from major U.S. retailers and brand manufacturers. As the name implies, the company specializes in high-volume truckload transactions that offer buyers the lowest possible per-unit cost, making it an ideal sourcing partner for established resellers and wholesale operations with the warehouse capacity and sales channels to handle large-volume purchases. Product categories span electronics, home goods, toys, tools, health and beauty, apparel, outdoor equipment, and general merchandise, with loads sourced from major retail return centers across the country. Wholesale Truckload Liquidators serves buyers nationwide, coordinating shipments from multiple warehouse locations to minimize freight costs. The company caters to bin store chains, discount retail operations, Amazon FBA power sellers, eBay power sellers, international export buyers, and wholesale distributors who purchase at truckload scale. Each load includes manifest documentation and condition estimates to support informed purchasing decisions.`,

  77: `World Liquidators, Inc. is a wholesale liquidation company based in Wyoming, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major U.S. retailers and brand manufacturers. The company provides inventory across a broad range of product categories including electronics, home goods, toys, tools, health and beauty, apparel, outdoor and sporting goods, and general merchandise. World Liquidators serves both domestic resellers and international buyers, maintaining sourcing relationships that provide consistent access to fresh inventory at competitive wholesale liquidation pricing. The Wyoming location offers a lower-cost operating base that translates into competitive pricing for buyers, while centrally positioned freight routes provide reasonable shipping rates to the West Coast, Midwest, and Mountain West regions. World Liquidators serves Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and international export buyers looking for U.S.-sourced merchandise. The company offers both manifested and unmanifested lot options in various quantities, with warehouse pickup and freight delivery available.`,

  78: `Xcess Limited is a wholesale liquidation company based in Wooster, Ohio, specializing in customer returns, overstock, and excess inventory from major retailers and consumer brands. The company offers pallets and truckloads across a diverse set of product categories including electronics, home goods, health and beauty, toys, tools, apparel, outdoor equipment, and general merchandise. Xcess Limited has built its business around efficient handling of excess and surplus merchandise, working with retailers and manufacturers who need reliable channels to recover value from inventory that has left the traditional retail pipeline. The Wooster, Ohio, location provides excellent Midwest logistics access with competitive freight rates to Pennsylvania, Michigan, Indiana, West Virginia, and the broader eastern United States. Xcess Limited serves a variety of buyers including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount store owners, and wholesale distributors looking for quality surplus inventory at wholesale liquidation prices. Warehouse pickup and nationwide freight delivery are both available for all lot sizes.`,

  79: `Worldly Treasures Liquidators, INC is a wholesale liquidation company based in Burbank, California, in the greater Los Angeles metro area, offering pallets and truckloads of customer returns, overstock, and closeout merchandise from major retailers and brand manufacturers. The company provides a wide product selection spanning electronics, home goods, health and beauty, apparel, toys, tools, housewares, and general merchandise, sourced from the massive retail and e-commerce return streams flowing through Southern California. Worldly Treasures' Burbank location provides proximity to major entertainment, retail, and logistics hubs, with convenient access to the ports of Long Beach and Los Angeles for international export buyers. The company serves a diverse buyer community including Amazon FBA sellers, eBay resellers, Whatnot livestream sellers, bin store operators, flea market vendors, discount retailers, and international export buyers who consolidate container loads from Southern California for worldwide shipping. Worldly Treasures Liquidators offers competitive pricing on both manifested and unmanifested lots, with warehouse pickup available locally and freight delivery coordinated nationwide.`,

  // Note: supplier 57 (RDW Liquidation) is already included above
};

async function main() {
  console.log(`\n=== Apply Supplier Descriptions ===`);
  console.log(`Mode: ${DRY_RUN ? 'DRY RUN' : 'LIVE'}\n`);

  try {
    await prisma.$queryRaw`SELECT 1`;
    console.log('Database connection OK\n');
  } catch (error: any) {
    console.error('Database connection FAILED:', error.message);
    process.exit(1);
  }

  let updated = 0;
  let skipped = 0;
  let failed = 0;

  const supplierIds = Object.keys(DESCRIPTIONS).map(Number).sort((a, b) => a - b);
  console.log(`Processing ${supplierIds.length} supplier descriptions...\n`);

  for (const id of supplierIds) {
    const description = DESCRIPTIONS[id];
    const wordCount = description.split(/\s+/).length;

    try {
      const supplier = await prisma.supplier.findUnique({
        where: { id },
        select: { id: true, name: true, description: true },
      });

      if (!supplier) {
        console.log(`  SKIP id=${id}: not found in DB`);
        skipped++;
        continue;
      }

      const currentWords = supplier.description ? supplier.description.split(/\s+/).length : 0;

      if (currentWords >= 150) {
        console.log(`  SKIP ${supplier.name} (already ${currentWords} words)`);
        skipped++;
        continue;
      }

      console.log(`  ${supplier.name}: ${currentWords}w -> ${wordCount}w`);

      if (!DRY_RUN) {
        await prisma.supplier.update({
          where: { id },
          data: { description },
        });
      }
      updated++;
    } catch (error: any) {
      console.error(`  FAILED id=${id}: ${error.message}`);
      failed++;
    }
  }

  console.log(`\n=== Results ===`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Skipped: ${skipped}`);
  console.log(`  Failed: ${failed}`);
  console.log(`  Total: ${supplierIds.length}\n`);

  await prisma.$disconnect();
}

main().catch((error) => {
  console.error('Fatal error:', error);
  prisma.$disconnect();
  process.exit(1);
});
