// Auto-generated seed data with enhanced suppliers from seed.ts
// Generated on: 2025-11-14T02:39:45.852Z
// This file contains 6 enhanced suppliers with complete data
// and 78 additional wholesalers

export const wholesalerSuppliers = [
  {
    "name": "B-Stock Supply",
    "slug": "bstock-supply",
    "shortDescription": "Marketplace access to national retailer returns with detailed manifests.",
    "description": "B-Stock powers private marketplace liquidation programs for the world's largest retailers and brands. Buyers gain vetted access to mixed-category returns, closeouts, and refurb inventory with manifest visibility and online auction controls.",
    "website": "https://bstock.com/supply",
    "phone": "(855) 890-7264",
    "email": "support@bstock.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.6,
    "reviewCount": 2,
    "trustScore": 92,
    "minimumOrder": "Single pallet auction wins",
    "leadTime": "Ships within 3 business days of payment",
    "specialties": [
      "Manifested auctions",
      "Retailer-direct loads",
      "Global buyer network"
    ],
    "certifications": [
      "R2 downstream partners",
      "Data wipe compliance"
    ],
    "badges": [
      "Verified manifests",
      "Digital bidding"
    ],
    "logisticsNotes": "Loads depart from multiple retailer hubs; buyer selects carrier or utilizes B-Stock recommended partners.",
    "pricingNotes": "Auction format with dynamic pricing. Winning bids require 10% buyer premium plus transport arranged by buyer.",
    "homeRank": 1,
    "regionId": null
  },
  {
    "name": "888 Lots",
    "slug": "888-lots",
    "shortDescription": "Fixed-price manifested lots with profit analytics and ready-to-ship cartons.",
    "description": "888 Lots offers manifest-driven lots for Amazon resellers and online merchants. Every lot includes profit estimations, condition grading, and prep services for FBA-ready shipments.",
    "website": "https://www.888lots.com",
    "phone": "(888) 821-6577",
    "email": "sales@888lots.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.75,
    "reviewCount": 2,
    "trustScore": 94,
    "minimumOrder": "$1,200 first purchase",
    "leadTime": "Ships within 48 hours from NJ warehouse",
    "specialties": [
      "Amazon profitability data",
      "Lot customization",
      "FBA prep services"
    ],
    "certifications": [
      "ISO 9001 warehouse processes"
    ],
    "badges": [
      "Prep center ready",
      "Live profit calculator"
    ],
    "logisticsNotes": "Destockify buyers can opt into pallet consolidation or direct parcel shipping for micro-lots destined for prep centers.",
    "pricingNotes": "Fixed price lots updated daily. Negotiation available for recurring buyers purchasing 5+ lots per week.",
    "homeRank": 2,
    "regionId": null
  },
  {
    "name": "Quicklotz",
    "slug": "quicklotz",
    "shortDescription": "Nationwide pallet program with bin-store-friendly surprise mixes.",
    "description": "Quicklotz curates mystery boxes, pallets, and truckloads tailored for bin stores, discount shops, and online live sellers. Buyers choose from premium, general, and treasure hunt mixes released weekly.",
    "website": "https://quicklotz.com",
    "phone": "(864) 469-4500",
    "email": "hello@quicklotz.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.2,
    "reviewCount": 2,
    "trustScore": 88,
    "minimumOrder": "$650 pallet or 10 mystery boxes",
    "leadTime": "Outbound within 72 hours from GA or TX",
    "specialties": [
      "Mystery pallets",
      "Surprise apparel mixes",
      "Live-sale ready lots"
    ],
    "certifications": [],
    "badges": [
      "Same-day pickup",
      "Truckload builder"
    ],
    "logisticsNotes": "Buyers can pick up at GA or TX warehouses with forklift assistance. Quicklotz can bundle multiple pallets into mixed truckloads.",
    "pricingNotes": "Fixed pallet pricing with weekly specials. Membership discounts stack for buyers committing to monthly subscription.",
    "homeRank": 3,
    "regionId": null
  },
  {
    "name": "Via Trading",
    "slug": "via-trading",
    "shortDescription": "Los Angeles liquidation hub with bilingual support and export services.",
    "description": "Via Trading specializes in apparel, tools, and general merchandise pallets with options for walk-through inspections and export consolidation. Their bilingual sales team supports Latin American buyers and U.S. discount chains alike.",
    "website": "https://www.viatrading.com",
    "phone": "(877) 202-3616",
    "email": "sales@viatrading.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.4,
    "reviewCount": 1,
    "trustScore": 86,
    "minimumOrder": "$500 (in-person) / $1,200 (shipped)",
    "leadTime": "Same-day pickup or ship within 48 hours",
    "specialties": [
      "Export consolidation",
      "Spanish-language support",
      "Inspection program"
    ],
    "certifications": [
      "Customs bonded facility"
    ],
    "badges": [
      "Export friendly",
      "On-site inspection"
    ],
    "logisticsNotes": "Offers on-site loading, cross-docking, and optional drop-trailer for frequent buyers. Export docs prepared in-house.",
    "pricingNotes": "Pricing tiers based on volume. Drop trailer customers receive volume discounts on consistent weekly pulls.",
    "homeRank": 4,
    "regionId": null
  },
  {
    "name": "Direct Liquidation",
    "slug": "direct-liquidation",
    "shortDescription": "Big-box retailer returns with recurring truckload programs nationwide.",
    "description": "Direct Liquidation manages contract returns for major retailers and manufacturers. Buyers secure recurring truckload programs with graded conditions and optional refurbishment services.",
    "website": "https://www.directliquidation.com",
    "phone": "(800) 679-9451",
    "email": "support@directliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.5,
    "reviewCount": 1,
    "trustScore": 90,
    "minimumOrder": "Full truckload commitment",
    "leadTime": "3-5 business days from contract acceptance",
    "specialties": [
      "Contract truckload programs",
      "Refurb warranties",
      "Retailer-direct relationships"
    ],
    "certifications": [
      "ISO 14001 recycling processes"
    ],
    "badges": [
      "Contract ready",
      "Nationwide locations"
    ],
    "logisticsNotes": "Offers contracted weekly truckloads from Southeast, Midwest, and Pacific Northwest facilities with routed carrier options.",
    "pricingNotes": "Pricing negotiated per lane and commodity. Volume commitments unlock blended cost-per-unit improvements over time.",
    "homeRank": 5,
    "regionId": null
  },
  {
    "name": "Wholesale Ninety",
    "slug": "wholesale-ninety",
    "shortDescription": "Boutique micro-lots curated for social sellers and subscription boxes.",
    "description": "Wholesale Ninety sources brand-consistent micro-lots of beauty, wellness, and lifestyle goods curated for social commerce. Every box includes storytelling angles, product cards, and suggested resale pricing.",
    "website": "https://wholesaleninety.com",
    "phone": "(929) 412-0090",
    "email": "hello@wholesaleninety.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 4.8,
    "reviewCount": 1,
    "trustScore": 84,
    "minimumOrder": "5 curated boxes ($750)",
    "leadTime": "Ships within 72 hours from NJ studio",
    "specialties": [
      "Story-driven curation",
      "Product photography add-ons",
      "Subscription-ready assortments"
    ],
    "certifications": [
      "SQF Level 2 partner warehouse"
    ],
    "badges": [
      "Curated storytelling",
      "Subscription-first"
    ],
    "logisticsNotes": "Includes optional kitting for subscription boxes and drop shipping direct to influencers or sales hosts.",
    "pricingNotes": "Pricing includes curation fee. Volume subscribers receive seasonal previews and early access to themed drops.",
    "homeRank": 6,
    "regionId": null
  },
  {
    "name": "Liquidation.com",
    "slug": "liquidationcom",
    "shortDescription": null,
    "description": "Liquidation.com, a Liquidity Services marketplace, hosts online auctions for surplus and returned inventory from major retailers, with multiple warehouse locations and truckload, pallet, and case-lot buying options for resellers.",
    "website": "https://www.liquidation.com",
    "phone": "1-800-310-4604",
    "email": "Info@LiquidityServices.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Fr8Auctions",
    "slug": "fr8auctions",
    "shortDescription": null,
    "description": "Fr8Auctions runs large-scale wholesale freight auctions in the Southeast, selling truckload quantities of customer returns, overstocks, and salvage across home improvement, tools, appliances, and more.",
    "website": "https://fr8auctions.com",
    "phone": "(404) 808-5458",
    "email": "Join@fr8auctions.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Department Store Liquidations",
    "slug": "departmentstoreliquidations",
    "shortDescription": null,
    "description": "Department Store Liquidations sources truckloads direct from U.S. distribution centers (Target, Amazon, Lowe’s and more), supplying bin stores and discount retailers with high‑margin, fast‑moving loads.",
    "website": "https://www.departmentstoreliquidations.com",
    "phone": "1-800-567-9392; 718-513-0128",
    "email": "sales@departmentstoreliquidations.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "JD Closeouts",
    "slug": "jdcloseouts",
    "shortDescription": null,
    "description": "JD Closeouts supplies mixed closeout lots and truckloads of general merchandise, apparel, HBA, toys, and more from major retailers for flea markets, discount stores, and e‑commerce sellers.",
    "website": "http://jdcloseouts.com",
    "phone": "(954) 581-2702",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Merchandize Liquidators",
    "slug": "merchandizeliquidators",
    "shortDescription": null,
    "description": "Merchandize Liquidators offers wholesale pallets and truckloads of returns, shelf‑pulls, and excess inventory—specializing in apparel, HBA, and general merchandise—with nationwide freight and export support.",
    "website": "https://www.merchandizeliquidators.com",
    "phone": "1-800-218-9596",
    "email": "sales@merchandizeliquidators.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Discount Wholesalers Inc",
    "slug": "discountwholesalersinc",
    "shortDescription": null,
    "description": "Discount Wholesalers Inc is a North Carolina-based closeout and liquidation supplier selling case lots, pallets, and truckloads to resellers, with regular walk‑in days and active social channels.",
    "website": "https://discountwholesalersinc.com",
    "phone": "#ERROR!",
    "email": "sales@discountwholesalersinc.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "DNC Wholesale",
    "slug": "dncwholesale",
    "shortDescription": null,
    "description": "DNC Wholesale distributes designer and brand‑name closeouts and liquidation merchandise—handbags, clothing, shoes, and accessories—for boutiques, online sellers, and exporters.",
    "website": "https://www.dncwholesale.com",
    "phone": "(954) 300-1855",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "RL Liquidators",
    "slug": "rlliquidators",
    "shortDescription": null,
    "description": "RL Liquidators provides omni‑channel liquidation and reverse logistics solutions including managed truckload programs, bin stores, and online auctions (BidRL/Falling Prices) with brand‑protection focus.",
    "website": "https://www.rlliquidators.com",
    "phone": "916-747-7762",
    "email": "info@rlliquidators.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Inmar Liquidates",
    "slug": "inmarliquidates",
    "shortDescription": null,
    "description": "Inmar Liquidates (Inmar Intelligence) sells truckloads and pallets of retailer returns, overstocks, and seasonal inventory via a B2B platform backed by Inmar’s nationwide returns processing network.",
    "website": "https://inmarliquidates.com",
    "phone": null,
    "email": "solutions@inmar.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Select Liquidation",
    "slug": "selectliquidation",
    "shortDescription": null,
    "description": "Select Liquidation brokers direct‑shipped truckloads from major retailers like Amazon, Target, and Lowe’s, focusing on transparent sourcing, buyer education, and optimized loads for bin stores and discount retailers.",
    "website": "https://selectliquidation.com",
    "phone": "(800) 224-3094",
    "email": "support@selectliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "AAA Closeout Liquidators",
    "slug": "aaacloseoutliquidators",
    "shortDescription": null,
    "description": "AAA Closeout Liquidators (est. 1979) buys and sells excess inventory, closeouts, and customer returns from major retailers, offering global export services and reliable liquidation sourcing.",
    "website": "https://aaacloseout.com",
    "phone": "518-217-8587",
    "email": "sales@aaacloseout.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Ace Liquidation",
    "slug": "aceliquidation",
    "shortDescription": null,
    "description": "Ace Liquidation serves discount retailers and resellers with pallets and truckloads of general merchandise sourced from regional returns and overstocks, with frequent in‑person sales events.",
    "website": "https://www.facebook.com/AcesLiquidation/",
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "ALL Wholesale LLC",
    "slug": "allwholesalellc",
    "shortDescription": null,
    "description": "ALL Wholesale LLC supplies wholesale liquidation inventory including overstock, returns, and closeouts to bin stores, export buyers, and discount resellers with an emphasis on fast‑moving categories.",
    "website": "https://www.allwholesalellc.com/",
    "phone": "18882983682",
    "email": "pliquidation34@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "All Prime Products",
    "slug": "allprimeproducts",
    "shortDescription": null,
    "description": "All Prime Products specializes in hardgoods liquidation, sourcing excess inventory from major retailers and offering mixed pallets and truckloads to resellers and e‑commerce sellers seeking margin expansion.",
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "American Liquidations",
    "slug": "americanliquidations",
    "shortDescription": null,
    "description": "American Liquidations offers a broad range of liquidation lots including electronics, appliances, and general merchandise direct from retail streams, with options for manifested pallets and truckloads.",
    "website": "https://www.americanliquidations.com/",
    "phone": "203-587-4132",
    "email": "Sales@americanliquidaitons.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "American Merchandise Liquidators",
    "slug": "americanmerchandiseliquidators",
    "shortDescription": null,
    "description": "American Merchandise Liquidators provides overstock and closeout inventory solutions for resellers, flea market vendors, and discount stores, focusing on mixed freight and high‑velocity categories.",
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "American Pallet Liquidators",
    "slug": "americanpalletliquidators",
    "shortDescription": null,
    "description": "American Pallet Liquidators specializes in pallet and truckload wholesale liquidation for independent retailers and resellers, offering customer returns, shelf‑pulls, and overstock with nationwide shipping.",
    "website": "https://aplpallets.com/",
    "phone": "(502) 208-1035",
    "email": "Brett@bidonpallets.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Archer Logistix",
    "slug": "archerlogistix",
    "shortDescription": null,
    "description": "Archer Logistix delivers logistics‑centric liquidation solutions including pallet and truckload sourcing, shipping consolidation, and nationwide freight services for high‑volume resellers.",
    "website": "https://www.archerlogistix.com/",
    "phone": "(773)963-1378",
    "email": "hello@archerlogistix.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "AXI Wholesale",
    "slug": "axiwholesale",
    "shortDescription": null,
    "description": "AXI Wholesale is a liquidation supplier focused on discount lot and truckload sales of overstock and returns, supporting resellers with streamlined purchasing and consistent supply.",
    "website": "https://www.axiwholesale.com/",
    "phone": "440 645 3466",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Barangle Corporation",
    "slug": "baranglecorporation",
    "shortDescription": null,
    "description": "Barangle Corporation \nBarangle Corporation is a liquidation and wholesale company based at 1140 York Road, Warminster, PA 18974. They buy excess inventory, overstock, returns, shelf-pulls, and closeout items from major retailers, then sell them in mixed pallets and full truckloads.\n\nTheir customers are usually resellers, discount stores, thrift stores, and e-commerce sellers who want bulk merchandise at lower cost. They don’t pick through the loads—they sell them as they receive them.\n\nThey offer things like general merchandise, overstock items, seasonal closeouts, customer returns, and mixed loads with a high piece count. They can also ship loads to surrounding states like NJ, NY, OH, and DE.",
    "website": "https://barangle.com/contact-us/",
    "phone": "267-217-7634",
    "email": "barangle.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Bin Store Merchandise",
    "slug": "binstoremerchandise",
    "shortDescription": null,
    "description": "Bin Store Merchandise is a type of liquidation-retail business that buys large lots of overstock, returns, and clearance goods from major retailers, then sells them at steep discounts. Shoppers often “dig through the bins” of mixed merchandise and purchase items at very low prices—sometimes just a few dollars.",
    "website": "https://www.binstoremerchandise.com/",
    "phone": "1-800-456-9492",
    "email": "sales@binstoremerchandise.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Black Swamp Liquidation",
    "slug": "blackswampliquidation",
    "shortDescription": null,
    "description": "Black Swamp Liquidation LLC is a wholesale liquidation company based in Bowling Green, Ohio. They acquire large lots of excess inventory such as overstock, shelf pulls, retailer returns and clearance items — then resell them in truckloads or bulk to resellers, discount stores or e-commerce sellers seeking low-cost inventory.",
    "website": "https://www.bsliq.com/",
    "phone": "844) 694-4669",
    "email": "sales@bsliq.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Boxflipz",
    "slug": "boxflipz",
    "shortDescription": null,
    "description": "Box Flipz is a liquidation-retail business based in Pennsylvania that sells overstock, returns, mystery boxes and wholesale pallets. They offer a “bin store” experience (lots of mixed merchandise at low cost) and also cater to resellers and bulk buyers.",
    "website": "https://boxflipz.com/",
    "phone": "412-206-1239",
    "email": "sales@boxflipz.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Brand Name Bargains, LLC",
    "slug": "brandnamebargainsllc",
    "shortDescription": null,
    "description": "Brand Name Bargains, LLC is a trusted liquidation company offering a wide range of high-quality, brand-name merchandise at discounted prices. Their inventory includes electronics, appliances, furniture, home décor, apparel, toys, and general merchandise, sourced from overstock, shelf-pulls, and closeouts from major national retailers. Serving resellers and bargain hunters alike, Brand Name Bargains provides reliable access to premium products in flexible quantities, making it an ideal destination for wholesale, resale, or clearance needs.",
    "website": "https://www.bbb.org/us/ny/brooklyn/profile/liquidators/brand-name-bargains-llc-0121-120405",
    "phone": "718-513-0128",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "COHO Liquidation",
    "slug": "coholiquidation",
    "shortDescription": null,
    "description": "COHO Liquidation, based in Sedro‑Woolley, Washington, is a wholesale and retail liquidation company offering high-volume pallets and truckloads of overstock, returns, freight salvage, and manufacturer overruns. Their inventory spans electronics, furniture, tools, baby & childcare items, automotive supplies, health & beauty, pet products, home décor, outdoor gear, and general merchandise. Sourced from major retailers, manufacturers, and large-box stores, COHO provides resellers and bargain hunters the opportunity to purchase brand-name merchandise in bulk at deep discounts.",
    "website": "https://www.coholiquidation.com/",
    "phone": "360 542 4122",
    "email": "https://www.ebay.com/str/coholiquidation",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Comprehensive Liquidation",
    "slug": "comprehensiveliquidation",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Continental Wholesale",
    "slug": "continentalwholesale",
    "shortDescription": null,
    "description": "Continental Wholesale LLC, based in Hampton, Iowa, is a Midwest liquidation company offering pallets and truckloads of overstock, shelf-pulls, returns, and salvage inventory from major retailers like Walmart, Target, Home Depot, Menards, and Amazon. Their inventory includes electronics, appliances, furniture, home décor, tools, toys, apparel, and general merchandise. Serving resellers, e‑commerce sellers, discount and thrift stores, Continental Wholesale provides brand-name goods in bulk at discounted prices with reliable shipping across the U.S.",
    "website": "https://www.continentalwholesale.com/",
    "phone": "(641) 456-3165",
    "email": "continentalwholesale@yahoo.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Discount Truckloads",
    "slug": "discounttruckloads",
    "shortDescription": null,
    "description": "Discount Truckloads, based in Dallas, Texas, is a wholesale liquidation supplier offering pallets and truckloads of overstock, returns, and shelf-pull merchandise from major retailers. Their inventory includes electronics, appliances, home décor, sporting goods, toys, tools, apparel, and general merchandise. They provide brand-name bulk lots at competitive margins, ideal for resellers, discount stores, and e-commerce businesses.",
    "website": "https://www.dtlots.com/",
    "phone": "800-608-6525",
    "email": "sales@dtlots.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "East Coast Liquidators",
    "slug": "eastcoastliquidators",
    "shortDescription": null,
    "description": "East Coast Liquidators in Vero Beach, Florida, is a wholesale liquidation company offering pallets and truckloads of overstock, returns, and close-out inventory from major retailers. Their products include brand-name apparel, footwear, accessories, tools, home goods, furniture, health & beauty, and general merchandise. Ideal for resellers and e-commerce sellers, they provide high-margin bulk merchandise sourced directly from large-box stores and manufacturers.",
    "website": "https://ecliquidators.com/",
    "phone": "(772) 501-2148",
    "email": "eclkerry@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Excess4Less",
    "slug": "excess4less",
    "shortDescription": null,
    "description": "Excess4Less, based in Virginia, is a wholesale liquidation company offering pallets and truckloads of overstock, shelf-pulls, returns, and excess inventory from major retailers and big-box stores. Their products include electronics, apparel, footwear, toys, home décor, furniture, tools, pet supplies, health & beauty, and general merchandise. They provide brand-name bulk lots at competitive prices, ideal for resellers, discount stores, and e-commerce sellers.",
    "website": "http://excesstruckloads.com/",
    "phone": "860-508-2549",
    "email": "sales@excess",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Freedom Wholesale",
    "slug": "freedomwholesale",
    "shortDescription": null,
    "description": "Freedom Wholesale is a liquidation and overstock provider offering pallets and truckloads of excess, shelf-pull, and return inventory from major national retailers. Their products include electronics, home décor, furniture, tools, sporting goods, toys, apparel, baby items, and general merchandise. Ideal for resellers, e-commerce sellers, and discount retailers, Freedom Wholesale delivers brand-name bulk merchandise at competitive prices.",
    "website": "https://www.freedomwholesale.com/wholesale/home_page",
    "phone": "855-915-4800",
    "email": "Wholesale@FreedomWholesale.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "GBY Liquidations",
    "slug": "gbyliquidations",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Genco Marketplace",
    "slug": "gencomarketplace",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "GRP Liquidations",
    "slug": "grpliquidations",
    "shortDescription": null,
    "description": "GRP Liquidations, based in Grand Rapids, Michigan, offers pallets and truckloads of excess inventory, returns, shelf-pulls, and overstock from major retailers and big-box stores. Their products include electronics, apparel, footwear, toys, home goods, tools, pet supplies, health & beauty, and general merchandise. Catering to resellers and e-commerce sellers, GRP provides brand-name bulk merchandise at competitive prices with fast inventory turnover.",
    "website": "https://grpliquidations.com/",
    "phone": "616-209-8117",
    "email": "info@grpliquidations.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "HJ Liquidators Closeouts",
    "slug": "hjliquidatorscloseouts",
    "shortDescription": null,
    "description": "HJ Liquidators & Closeouts, based in Des Plaines, Illinois, offers pallets and truckloads of overstock, returns, shelf‑pulls, and end‑of‑season inventory from major retailers and big-box stores. Their products include electronics, apparel, footwear, toys, home décor, furniture, tools, office supplies, health & beauty, and general merchandise. Serving resellers, e-commerce sellers, and specialty retailers, HJ provides brand-name bulk merchandise at competitive prices with fast nationwide shipping.",
    "website": "https://www.hjcloseouts.com/",
    "phone": "224 567 6030",
    "email": "support@hjcloseouts",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Ice Liquidation",
    "slug": "iceliquidation",
    "shortDescription": null,
    "description": "Ice Liquidation, based in Pompano Beach, Florida, supplies high-volume pallets and truckloads of overstock, returns, and shelf-pulls from major big-box retailers. Their inventory includes electronics, apparel, footwear, toys, home goods, small appliances, and general merchandise. Serving resellers, discount stores, and online sellers, Ice Liquidation offers brand-name bulk merchandise at deep discounts with flexible pallet and case lot options.",
    "website": null,
    "phone": null,
    "email": "liqloads@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "IDX Liquidations",
    "slug": "idxliquidations",
    "shortDescription": null,
    "description": "IDX Liquidations, located in Maspeth, New York, is a wholesale liquidation supplier offering pallets, truckloads, and mixed lots of overstock, returns, and shelf-pulls from major retailers like Walmart, Target, JCPenney, and Macy’s. Their inventory includes electronics, appliances, furniture, apparel, toys, health & beauty, kitchen goods, tools, and general merchandise. Ideal for e-commerce sellers, flea-market vendors, and discount stores, IDX provides brand-name bulk merchandise at competitive prices with flexible lot sizes for resale.",
    "website": null,
    "phone": "347-205-8481.",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "J&M Liquidation LLC",
    "slug": "jmliquidationllc",
    "shortDescription": null,
    "description": "J&M Liquidation LLC supplies pallets and truckloads of overstock, returns, and shelf-pulls from major national retailers. Their inventory includes electronics, furniture, household goods, toys, tools, apparel, and general merchandise. Serving resellers, auction houses, and e-commerce sellers, J&M offers brand-name bulk merchandise at competitive prices with fast nationwide shipping.",
    "website": "https://jmliquidationllc.com/",
    "phone": "(843) 796-2139",
    "email": "sales@jmliquidationllc.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Keystone Liquidators",
    "slug": "keystoneliquidators",
    "shortDescription": null,
    "description": "Keystone Liquidators is a wholesale liquidation company offering pallets and truckloads of overstock, returns, shelf-pulls, and close-out inventory from major big-box retailers. Their products include electronics, appliances, furniture, apparel, footwear, toys, tools, pet supplies, health & beauty, and general merchandise. Serving resellers, discount stores, and e-commerce sellers, Keystone provides brand-name bulk merchandise at competitive prices for scalable resale.",
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "LiquidateNow",
    "slug": "liquidatenow",
    "shortDescription": null,
    "description": "LiquidateNow helps manufacturers, distributors, and retailers clear overstock, shelf-pulls, and returns through wholesale solutions. Their inventory includes electronics, appliances, apparel, footwear, home décor, furniture, toys, tools, pet supplies, and general merchandise. Sourced from major retailers and big-box stores, LiquidateNow offers pallets, mixed case-lots, and truckloads of brand-name goods at competitive prices, ideal for resellers, discount stores, and e-commerce sellers.",
    "website": "https://liquidatenow.com/",
    "phone": "877-288-3863",
    "email": "info@liquidatenow.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Liquidation Brokers LLC",
    "slug": "liquidationbrokersllc",
    "shortDescription": null,
    "description": "Liquidation Brokers LLC, based in Mentor, Ohio, offers pallets, cases, and truckloads of overstock, returns, shelf-pulls, and close-out inventory from major retailers and big-box stores. Their products include electronics, appliances, furniture, apparel, toys, tools, pet supplies, health & beauty, and general merchandise. Serving resellers, discount stores, and e-commerce sellers, they provide brand-name bulk merchandise at competitive prices for scalable resale.",
    "website": null,
    "phone": "1 800-976-7502",
    "email": "sales@Liquidation-Brokers.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Liquidation Closeouts",
    "slug": "liquidationcloseouts",
    "shortDescription": null,
    "description": "Liquidation Closeouts is a business that offers bulk lots and discounted inventory from overstock, shelf‑pulls, and returns. They cater to resellers, discount stores, and e‑commerce sellers looking for brand‑name goods in bulk at lower cost.",
    "website": null,
    "phone": "1 813-526-6808",
    "email": "silvacreations01@yahoo.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Liquidation Deals Canada",
    "slug": "liquidationdealscanada",
    "shortDescription": null,
    "description": "Liquidation Deals Canada, based in North York, Ontario, supplies pallets and bulk loads of overstock, returns, shelf pulls, and liquidation inventory from major Canadian retailers. Their products include electronics, appliances, apparel, toys, home décor, furniture, and general merchandise. Ideal for resellers, discount stores, and e-commerce sellers, they offer brand-name bulk merchandise at competitive prices with fast delivery across Canada.",
    "website": "https://liquidationdeals.ca/",
    "phone": "1(647)544-1235",
    "email": "Info@liquidationdeals.ca",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Liquidators USA",
    "slug": "liquidatorsusa",
    "shortDescription": null,
    "description": "Liquidators USA, in Peachtree City, Georgia, supplies pallets, mixed cases, and truckloads of overstock, returns, and excess inventory from major retailers. Their products include appliances, electronics, furniture, tools, seasonal goods, and general merchandise. Ideal for resellers, discount stores, and e-commerce sellers, they offer brand-name bulk inventory at deep discounts with frequent new shipments and local delivery.",
    "website": "https://liquidatorsusa.com/",
    "phone": "1 770-502-6334",
    "email": "Michelle@liquidatorsusa.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "LiquidityApp",
    "slug": "liquidityapp",
    "shortDescription": null,
    "description": "LiquidityApp, based in Missouri City, Texas, is a B2B liquidation platform providing resellers and wholesalers access to pallets, cases, and truckloads of overstock, returns, shelf-pulls, and excess inventory from major retailers. Their products include electronics, apparel, appliances, home décor, furniture, sporting goods, health & beauty, pet supplies, and general merchandise. With a streamlined digital marketplace, secure payments, and nationwide logistics, LiquidityApp helps buyers scale inventory and maximize margins efficiently.",
    "website": "https://www.liquidityapp.com/?utm_source=chatgpt.com",
    "phone": "18327284494",
    "email": "info@liquidityapp.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Live Wire Liquidators",
    "slug": "livewireliquidators",
    "shortDescription": null,
    "description": "Live Wire Liquidators, LLC, in Lancaster, Ohio, offers pallets and truckloads of overstock, shelf‑pulls, and customer returns, specializing in discount flooring and home‑improvement inventory. Their products include laminate, vinyl, hardwood, tile, hardware, tools, and surplus display items. Sourced from major retailers and liquidation channels, Live Wire provides resellers, contractors, and value buyers with brand‑name bulk goods at deep discounts, supported by detailed manifests and regular Facebook listings.",
    "website": "https://www.livewireliquidators.com/",
    "phone": "740-785-4385",
    "email": "sales@livewireliquidators.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Marketplace Closeouts",
    "slug": "marketplacecloseouts",
    "shortDescription": null,
    "description": "Marketplace Closeouts, based in Hollywood, Florida, is a trusted wholesale liquidation company offering high-quality overstock, shelf pulls, and customer returns from top U.S. retailers. They supply manifested pallets and truckloads of home improvement goods, electronics, tools, apparel, furniture, toys, and general merchandise. With inventory sourced from major stores like Amazon, Walmart, Target, Home Depot, Lowe’s, and Costco, Marketplace Closeouts provides resellers and discount retailers with name-brand products at unbeatable prices. Known for reliability and great service, they make sourcing liquidation inventory simple and profitable.",
    "website": "https://www.hugedomains.com/index.cfm",
    "phone": "303-893-0552",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Marketplace Liquidation",
    "slug": "marketplaceliquidation",
    "shortDescription": null,
    "description": "Marketplace Liquidation is a trusted wholesale liquidation company offering high-quality overstock, shelf pulls, and customer returns from top U.S. retailers. They specialize in a wide range of categories, including home improvement, tools, electronics, furniture, clothing, and general merchandise. With both manifested pallets and full truckloads available, Marketplace Liquidation supplies resellers and discount store owners with name-brand inventory from major retailers like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco. Known for great prices, reliability, and excellent service, they make sourcing quality liquidation goods simple and profitable.",
    "website": "https://www.marketplaceliquidation.com/",
    "phone": "763-208-8724",
    "email": "sales@marketplaceliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Midtown Liquidation",
    "slug": "midtownliquidation",
    "shortDescription": null,
    "description": "Midtown Liquidation is a trusted wholesale liquidation company offering premium overstock, shelf pulls, and customer returns from major U.S. retailers. They supply manifested pallets and full truckloads of home improvement goods, electronics, appliances, furniture, tools, clothing, toys, and general merchandise. With inventory sourced from top stores like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco, Midtown Liquidation provides resellers and discount retailers with name-brand products at unbeatable prices. Known for transparency, great value, and excellent service, they help businesses grow through quality, affordable liquidation deals.",
    "website": null,
    "phone": "1 951-566-5534",
    "email": "midtownliquidation@aol.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Orotex Liquidation",
    "slug": "orotexliquidation",
    "shortDescription": null,
    "description": "Orotex Liquidation is a trusted wholesale liquidation company offering premium overstock, shelf pulls, and customer returns from top U.S. retailers. They supply manifested pallets and full truckloads of home improvement items, electronics, appliances, tools, furniture, apparel, toys, and general merchandise. With inventory sourced from major chains like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco, Orotex Liquidation provides resellers and discount stores with name-brand products at unbeatable prices. Known for transparency, great value, and excellent service, they help businesses grow through reliable, high-quality liquidation deals.",
    "website": "https://orotexliquidation.com/",
    "phone": "(305) 887-1486",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Overstocks Trading",
    "slug": "overstockstrading",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Premier Liquidation",
    "slug": "premierliquidation",
    "shortDescription": null,
    "description": "Premier Liquidation is a trusted wholesale liquidation company offering overstock, shelf pulls, and customer returns from top U.S. retailers. They provide pallets and full truckloads of home improvement items, electronics, appliances, furniture, tools, clothing, toys, and general merchandise. Sourced from major retailers like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco, Premier Liquidation supplies resellers and discount stores with name-brand products at competitive prices. Known for reliability and excellent service, they help businesses grow through high-quality, profitable liquidation inventory.",
    "website": null,
    "phone": null,
    "email": "premiereliquidationsllc@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Premier Wholesaler",
    "slug": "premierwholesaler",
    "shortDescription": null,
    "description": "Premier Wholesaler is a trusted wholesale liquidation company offering overstock, shelf pulls, and customer returns from top U.S. retailers. They provide pallets and truckloads of electronics, home improvement items, appliances, furniture, tools, clothing, toys, and general merchandise. Sourced from major retailers like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco, Premier Wholesaler supplies resellers and discount stores with name-brand products at competitive prices. Known for reliability and excellent service, they help businesses grow through high-quality liquidation inventory.",
    "website": "https://www.premierwholesaler.com/",
    "phone": "772-999-6086",
    "email": "SM@PremierWholesaler.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Quantum Commodities",
    "slug": "quantumcommodities",
    "shortDescription": null,
    "description": "Quantum Commodities is a trusted wholesale liquidation company offering overstock, shelf pulls, and customer returns from top U.S. retailers. They provide pallets and truckloads of electronics, home improvement items, appliances, furniture, tools, clothing, toys, and general merchandise. Sourced from major retailers like Amazon, Walmart, Target, Lowe’s, Home Depot, and Costco, Quantum Commodities supplies resellers and discount stores with name-brand products at competitive prices. Known for reliability and excellent service, they help businesses grow through high-quality, profitable liquidation inventory.",
    "website": "https://www.quantumcommodities.com/",
    "phone": "(678) 571-3715",
    "email": "admin@quantumcommodities.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "RDW Liquidation",
    "slug": "rdwliquidation",
    "shortDescription": null,
    "description": "RDW Liquidation is a trusted wholesale liquidation company offering overstock, shelf pulls, and customer returns from top U.S. retailers. They provide pallets and full truckloads of electronics, home improvement items, appliances, tools, furniture, clothing, toys, and general merchandise. Sourced from major retailers like Walmart, Target, Home Depot, Lowe’s, and Amazon, RDW Liquidation supplies resellers and discount stores with name-brand products at competitive prices. Known for reliability and excellent service, they help businesses grow through high-quality, profitable liquidation inventory.",
    "website": "rdwliquidations.com",
    "phone": null,
    "email": "morgan5.rdw@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "REMEX Liquidation Wholesale, Export, Overstock Sales",
    "slug": "remexliquidationwholesaleexportoverstocksales",
    "shortDescription": null,
    "description": "REMEX Liquidation is a leading wholesale and overstock specialist providing pallets and truckloads of electronics, home‑improvement goods, appliances, furniture, tools, apparel, toys, and general merchandise. Sourced from major U.S. retailers and e‑commerce platforms, REMEX supplies resellers, exporters, and discount buyers with name‑brand inventory at competitive prices. With locations in Texas and California and global export support, they offer reliable, high-demand liquidation products with fast turnaround and efficient logistics.",
    "website": "https://remexliquidation.com/",
    "phone": "434) 333-1545",
    "email": "sales@remexliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "RMW Liquidations",
    "slug": "rmwliquidations",
    "shortDescription": null,
    "description": "RMW Liquidations LLC is a trusted wholesale liquidation company in Shelbyville, Indiana, offering overstock pallets, shelf pulls, and customer returns from major U.S. retailers. They provide electronics, home improvement items, appliances, furniture, tools, clothing, toys, and general merchandise in both pallets and full truckloads. Sourced from national chains and e‑commerce platforms, RMW Liquidations supplies resellers and discount stores with name‑brand, in‑demand products at competitive prices, helping businesses scale with reliable, high-quality liquidation inventory.",
    "website": "https://rmwliquidationsllc.godaddysites.com/",
    "phone": "812-350-8328",
    "email": "rmwliquidations@yahoo.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Salvage Closeouts, Inc.",
    "slug": "salvagecloseoutsinc",
    "shortDescription": null,
    "description": "Salvage Closeouts, Inc., based in Brooklyn, New York, is a trusted liquidation and surplus merchandise provider offering a wide range of high-value inventory to resellers and bulk buyers. They specialize in apparel, footwear, toys, electronics, housewares, bedding, and mixed merchandise lots sourced from major U.S. department store returns, overstocks, and closeouts. Offering pallet and truck‑load quantities from over 100 national retailers, Salvage Closeouts provides buyers with flexible options to access brand-name inventory at deep discounts.",
    "website": "https://www.bbb.org/us/nj/elizabeth/profile/wholesale-industrial-products/salvage-closeouts-inc-0121-65332/addressId/109113?utm_source=chatgpt.com",
    "phone": "(800) 567-9844",
    "email": "marketing@iabbb.org",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "ShowMe Liquidation",
    "slug": "showmeliquidation",
    "shortDescription": null,
    "description": "ShowMe Liquidation LLC, a family‑owned brokerage in Missouri, supplies resellers and bulk buyers with quality close-out and return merchandise. Their inventory includes apparel, footwear, toys, electronics, housewares, bedding, and mixed merchandise lots sourced from major U.S. retailers and big-box stores. Buyers can access brand-name products at deep discounts with flexible pallet and bulk lot options.",
    "website": null,
    "phone": "417) 342‑1737.",
    "email": "showmeliquidationllc@gmail.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Smart Source Wholesale",
    "slug": "smartsourcewholesale",
    "shortDescription": null,
    "description": "Smart Source Wholesale is a leading liquidation and surplus merchandise provider, offering electronics, home goods, furniture, apparel, health & beauty items, grocery lots, and more. Sourcing from major retailers like Amazon, Target, Walmart, CVS, and Home Depot, they provide pallet- and truck-load deals from overstock, returns, and shelf pulls. With a focus on quality, transparency, and competitive pricing, Smart Source Wholesale helps buyers access brand-name merchandise at deep discounts with flexible purchasing options.",
    "website": "https://smartsourcewholesale.com/",
    "phone": "(310) 666-6612",
    "email": "info@smartsourcewholesale.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "SmartLots",
    "slug": "smartlots",
    "shortDescription": null,
    "description": "SmartLots is a leading liquidation marketplace providing resellers and bulk buyers with pallets and truckloads of high-value merchandise. They specialize in apparel, footwear, electronics, health & beauty, seasonal goods, and mixed merchandise lots, sourced from returns, overstock, and shelf pulls from major retailers like Kohl’s and Lowe’s. With regularly updated inventory and flexible purchasing options, SmartLots offers brand-name products at deep discounts, making it a scalable and reliable sourcing solution for the resale market.",
    "website": "https://liquidation.dsc.dhl.com/collections/all",
    "phone": "855-313-3610",
    "email": "inmarliq@inmar.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Southern Liquidation",
    "slug": "southernliquidation",
    "shortDescription": null,
    "description": "Southern Liquidation, based in Northwest Arkansas, provides resellers and bulk buyers with pallet and truck‑load inventory across categories like small appliances, baby products, toys, electronics, furniture, bedding, and general housewares. Sourced from overstock, returns, and liquidation programs from major retailers like Target and Amazon, they offer brand-name merchandise at deep discounts with flexible, scalable purchasing options, making them a trusted partner in the liquidation marketplace.",
    "website": "https://southernliquidation.com/",
    "phone": "479 380 8606",
    "email": "hello@southernliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Streamline Liquidations",
    "slug": "streamlineliquidations",
    "shortDescription": null,
    "description": "Streamline Liquidation, a family‑owned wholesaler in the Carolinas, supplies resellers and bulk buyers with surplus and return inventory across categories like apparel, electronics, furniture, housewares, grocery, HBA, tools, and mixed merchandise loads. Sourced from major national retailers via overstock, shelf-pulls, and customer returns, they offer brand-name goods at deep discounts in pallet and truck-load formats, providing a reliable solution for scaling inventory with quality close-out merchandise.",
    "website": "https://streamlineliquidation.com/",
    "phone": "910-850-5958",
    "email": "rlaris3u@live.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Supreme Liquidator",
    "slug": "supremeliquidator",
    "shortDescription": null,
    "description": "Supreme Liquidator, based in Warminster, Pennsylvania, provides resellers and bulk buyers with full truck-loads and pallet lots of high-value merchandise, including electronics, fitness equipment, sporting goods, housewares, furniture, appliances, tools, and outdoor items. Sourced from major national retailers through overstock, shelf-pulls, and customer returns, they offer brand-name inventory at deep discounts, delivering a reliable, scalable solution for businesses seeking quality liquidation stock.",
    "website": "supremeliquidator.com",
    "phone": "267-483-7240",
    "email": "Sales@SupremeLiquidator.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "That Liquidation Place",
    "slug": "thatliquidationplace",
    "shortDescription": null,
    "description": "That Liquidation Place, LLC provides resellers and bulk buyers with brand-name liquidation merchandise, including apparel, toys, electronics, small appliances, home goods, and mixed pallets. Sourced from major U.S. retailers through overstock, returns, and shelf-pulls, they offer flexible pallet and volume deals, giving buyers access to high-turn, recognizable inventory at deep discounts.",
    "website": "https://thatliquidationplace.com/",
    "phone": "833-533-4300",
    "email": "billing@thatliquidationplace.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "The Discount Warehouse (TDW)",
    "slug": "thediscountwarehousetdw",
    "shortDescription": null,
    "description": "The Discount Warehouse (TDW), based in Sunrise, Florida, offers resellers and bulk buyers a wide range of liquidation inventory, including department store returns, overstock, and surplus from top retailers like Amazon and Target. Their products cover apparel, electronics, small appliances, housewares, HBA, seasonal goods, and mixed pallets. TDW provides flexible pallet, multi-pallet, and truckload options with shipping support, giving buyers access to brand-name close-out merchandise at deep discounts.",
    "website": "tdwcloseouts.com",
    "phone": "954-746-8000",
    "email": "sales@tdwcloseouts.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "The Select Source",
    "slug": "theselectsource",
    "shortDescription": null,
    "description": "The Select Source is a trusted liquidation provider with over 15 years of experience, offering bulk lots of surplus, returns, and salvage inventory. Their products include electronics, tools, outdoor gear, and mixed merchandise pallets sourced from nationwide retailers and clearance programs. With multiple regional pickup locations and an online bidding platform, The Select Source provides resellers, exporters, and auction buyers with flexible, scalable access to brand-name goods at competitive prices.",
    "website": "theselectsource.com",
    "phone": "817-796-3333",
    "email": "info@theselectsource.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Trends Liquidation",
    "slug": "trendsliquidation",
    "shortDescription": null,
    "description": "Trends Liquidation, based in Houston, supplies resellers and bulk buyers with electronics, small appliances, furniture, toys, housewares, and mixed pallets sourced from overstock, returns, and shelf-pulls from major retailers. Offering flexible pallet and truck-load options, they provide businesses with easy access to brand-name close-out merchandise at deep discounts for scalable inventory growth.",
    "website": "https://trendsliquidation.com/",
    "phone": "832) 728-4494",
    "email": "info@trendsliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Truckload Liquidations",
    "slug": "truckloadliquidations",
    "shortDescription": null,
    "description": "Truckload Liquidations, based in Florida, provides resellers and bulk buyers with electronics, appliances, home goods, apparel, toys, and mixed pallets sourced from major U.S. retailers like Amazon, Macy’s, Target, and JCPenney. Offering full truck‑load and multi‑pallet options, their inventory from overstock, shelf‑pulls, and returns gives buyers scalable access to brand‑name close‑out merchandise at deep discounts.",
    "website": "orotexliquidation.com/truckload",
    "phone": "305-887-1486",
    "email": "hello@orotexliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "TruckloadDeals.com",
    "slug": "truckloaddealscom",
    "shortDescription": null,
    "description": "TruckloadDeals.com is a leading liquidation provider offering full truck‑loads and high‑count pallets for resellers, discount retailers, and bulk buyers. Their inventory includes electronics, apparel, appliances, housewares, tools, and mixed merchandise, sourced from major U.S. retailers like Amazon, Target, Walmart, and Home Depot. With scalable pallet and truck-load options, they provide brand-name liquidation merchandise at deep discounts.",
    "website": "https://www.truckloaddeals.com/",
    "phone": "1-888-674-9274",
    "email": "sales@truckloaddeals.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Unboxed Wholesale, LLC",
    "slug": "unboxedwholesalellc",
    "shortDescription": null,
    "description": "Unboxed Wholesale, LLC, based in Lebanon, Ohio, provides resellers and bulk buyers with truck‑loads and high-volume pallets of liquidated goods. Their inventory includes general merchandise, apparel, groceries, furniture, tools, HBA, housewares, and sporting goods sourced from major retailers like Walmart, Target, Amazon, Kohl’s, Meijer, and Home Depot. With flexible pallet-to-truckload options and handled shipping, Unboxed Wholesale offers scalable access to brand-name close-out inventory at competitive prices.",
    "website": "https://www.unboxedwholesale.com/",
    "phone": "(877) 862-6933",
    "email": "Sales@UnboxedWholesale.com\r\n\r\n​",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Up Liquidation",
    "slug": "upliquidation",
    "shortDescription": null,
    "description": "Up Liquidation, a U.S.-based company, offers resellers and bulk buyers mystery boxes, pallets, and mixed loads of brand-name close-out inventory. Their products include electronics, apparel, kids’ gear, toys, HBA, home goods, and general merchandise, sourced from retailers like Amazon, Target, and Walmart. With flexible bulk options, fast shipping, and weekly drops, Up Liquidation provides scalable access to high-turn merchandise at deep discounts.",
    "website": "https://www.upliquidation.com/",
    "phone": "945-256-1749",
    "email": "support@upliquidation.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "What a Bargain",
    "slug": "whatabargain",
    "shortDescription": null,
    "description": null,
    "website": "Facebook.com/backtothebargains",
    "phone": "518-816-9380",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Wholesale City",
    "slug": "wholesalecity",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": "0314-9262922",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Wholesale Truckload Liquidators",
    "slug": "wholesaletruckloadliquidators",
    "shortDescription": null,
    "description": null,
    "website": null,
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "World Liquidators, Inc.",
    "slug": "worldliquidatorsinc",
    "shortDescription": null,
    "description": null,
    "website": "http://www.4wholesaleusa.com/",
    "phone": null,
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Xcess Limited",
    "slug": "xcesslimited",
    "shortDescription": null,
    "description": "Xcess Limited, based in Wooster, Ohio, is a leading U.S. retail liquidation specialist offering high‑piece‑count truck‑loads and large pallet lots. Their inventory spans general merchandise, apparel, home improvement, groceries, sporting goods, and electronics, sourced from major retailers, online fulfillment centers, and big-box chains like Amazon. Serving resellers, discount retailers, and exporters, Xcess Limited provides scalable, cost-effective access to brand-name close-out merchandise with flexible purchasing and nationwide shipping.",
    "website": "https://xcesslimited.com/",
    "phone": "330-523-0087",
    "email": "sales@xcesslimited.com",
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  },
  {
    "name": "Worldly Treasures Liquidators, INC",
    "slug": "worldlytreasuresliquidatorsinc",
    "shortDescription": null,
    "description": "Worldly Treasures Liquidators, INC, based in Burbank, California, is a trusted wholesale liquidation partner offering full truck-loads and high-volume pallet lots. Their inventory includes electronics, general merchandise, apparel, home & garden items, and mixed lots, sourced from major U.S. retailers via returns, overstock, and liquidation programs. Serving resellers, discount retailers, and exporters, they provide brand-name close-out merchandise with quality-verified loads and nationwide shipping.",
    "website": "https://wtliquidators.com/",
    "phone": "323-413-7270",
    "email": null,
    "heroImage": null,
    "logoImage": null,
    "averageRating": 0,
    "reviewCount": 0,
    "trustScore": 50,
    "minimumOrder": null,
    "leadTime": null,
    "specialties": [],
    "certifications": [],
    "badges": [],
    "logisticsNotes": null,
    "pricingNotes": null,
    "homeRank": 0,
    "regionId": null
  }
];
